Repository tektoncd/cli, pull requests merged in 2019-07, with the labels that each got.

#127 Remove hacks from e2e tests
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/log_reader.go
  pkg/cmd/taskrun/logs_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#137 Fix "Did you mean this" for mistyped command
  pkg/cmd/root.go
  pkg/cmd/root_test.go
Labels: approved, cla: yes, lgtm, size/M

#135 Remove unnecessary dependencies
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#140 Reset the flags before adding to it
  pkg/cmd/root.go
  pkg/cmd/root_test.go
Labels: approved, cla: yes, lgtm, size/S

#141 Update cobra to v0.0.5
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#132 Do not panic when template fails to execute
  pkg/cmd/pipelinerun/describe.go
Labels: approved, cla: yes, lgtm, size/S

#128 Add resource list command
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_resource_list.md
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
  pkg/cmd/pipelineresource/pipelineresource.go
  pkg/cmd/pipelineresource/pipelineresource_test.go
  pkg/cmd/root.go
  pkg/cmd/root_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#149 Add a simple `Makefile` for development purpoes
  .gitignore
  Makefile
Labels: approved, cla: yes, lgtm, size/S

#150 Removes azure-container flag ref from docs
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_describe.md
  docs/cmd/tkn_pipeline_list.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_describe.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_pipelinerun_logs.md
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_resource_list.md
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_list.md
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_list.md
Labels: approved, cla: yes, lgtm, size/M

#153 Ensure GO111MODULE=on on verify-codegen.sh script
  hack/update-deps.sh
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#152 bump pipeline dependendency to 0.4.0
  go.mod
  go.sum
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/list_test.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/task/list_test.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs_test.go
  pkg/helper/pipelinerun/tracker_test.go
  pkg/helper/pods/container_test.go
  pkg/helper/pods/pod_test.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/artifact_bucket.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/artifact_pvc.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/build_gcs_resource.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/dag.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/image_resource.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/resource_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/task_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/artifacts/artifacts_storage.go
  vendor/github.com/tektoncd/pipeline/pkg/merge/merge.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/resources/image_exporter.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/resources/taskspec.go
  vendor/github.com/tektoncd/pipeline/test/README.md
  vendor/github.com/tektoncd/pipeline/test/builder/doc.go
  vendor/github.com/tektoncd/pipeline/test/builder/pipeline.go
  vendor/github.com/tektoncd/pipeline/test/builder/task.go
  vendor/github.com/tektoncd/pipeline/test/controller.go
  vendor/github.com/tektoncd/pipeline/test/e2e-common.sh
  vendor/github.com/tektoncd/pipeline/test/e2e-tests-yaml.sh
  vendor/github.com/tektoncd/pipeline/test/e2e-tests.sh
  vendor/github.com/tektoncd/pipeline/test/presubmit-tests.sh
  vendor/github.com/tektoncd/pipeline/test/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#156 Use our own completion for zsh
  pkg/cmd/completion/bash_completion.go
  pkg/cmd/completion/completion.go
  pkg/cmd/completion/zsh_completion.go
Labels: approved, cla: yes, lgtm, size/L

#158 Makefile: add a FORCE target before bin/*
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#162 Closes #59: Sort pipelineruns by Start Time
  pkg/cmd/pipelinerun/list.go
Labels: approved, cla: yes, lgtm, size/XS

#165 Ensure ClusterTask name is consistent throughout
  pkg/cmd/clustertask/list.go
  pkg/cmd/task/list.go
Labels: approved, cla: yes, lgtm, size/M

#166 Add a vendor target to make sure vendor are up-to-date…
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#167 Sort Taskruns by Start Time
  pkg/cmd/taskrun/list.go
Labels: approved, cla: yes, lgtm, size/XS

#169 Fixes segfaults for taskrun list
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#170 Correct Mac OS X Typo in README
  README.md
Labels: approved, cla: yes, lgtm, size/S

#175 Upgrade cli runtime dependency
  docs/cmd/tkn.md
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_list.md
  docs/cmd/tkn_pipeline_describe.md
  docs/cmd/tkn_pipeline_list.md
  docs/cmd/tkn_pipelinerun_describe.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_resource_list.md
  docs/cmd/tkn_task_list.md
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-clustertask-list.1
  docs/man/man1/tkn-clustertask.1
  docs/man/man1/tkn-pipeline-describe.1
  docs/man/man1/tkn-pipeline-list.1
  docs/man/man1/tkn-pipelinerun-describe.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-resource-list.1
  docs/man/man1/tkn-task-list.1
  docs/man/man1/tkn-taskrun-list.1
  docs/man/man1/tkn.1
  go.mod
  go.sum
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/jsonpath_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/json.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/jsonpath.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/builder.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/template_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#174 Fix case sensitive in resource list
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
Labels: approved, cla: yes, lgtm, size/S

#176 Improve sort feature in tr and pr list
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/task/list.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#177 Make sure we get only the latest release.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#173 Add resource describe command
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_resource_describe.md
  docs/man/man1/tkn-resource-describe.1
  docs/man/man1/tkn-resource.1
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelineresource/pipelineresource.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#155 Start pipeline from last pipelinerun params
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  go.sum
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#178 Remove FIXME comment from e2e-tests.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#180 tkn as a kubectl plugin
  README.md
Labels: approved, cla: yes, lgtm, size/S

#181 Symlink kubectl-tkn to tkn in brew
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#182 Add more linter to golangci-lint
  .errcheck.txt
  .golangci.yml
  cmd/docs/generate.go
  cmd/docs/md_docs.go
  pkg/cmd/completion/completion.go
  pkg/cmd/completion/zsh_completion.go
  pkg/cmd/pipelinerun/log_writer.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/taskrun/log_writer.go
  pkg/cmd/version/version.go
  pkg/formatted/color.go
  pkg/helper/pods/container.go
Labels: approved, cla: yes, lgtm, size/M

#184 Add type flag to resource list
  docs/cmd/tkn_resource_list.md
  docs/cmd/tkn_version.md
  docs/man/man1/tkn-resource-list.1
  docs/man/man1/tkn-version.1
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#189 Update `go.sum` file
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#188 Fix linter errors 🙀
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/logs_testutil.go
  pkg/cmd/pipelinerun/log_writer.go
  pkg/cmd/pipelinerun/logs.go
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M
