Repository tektoncd/cli, pull requests merged in 2019-05, with the labels that each got.

#18 Add test for pipeline list
  go.mod
  pkg/cmd/pipeline/list_test.go
  pkg/testutil/cobra.go
  pkg/testutil/test_params.go
Labels: approved, cla: yes, lgtm, size/L

#20 Show last pipeline-run details of pipeline
  go.mod
  go.sum
  pkg/cmd/dummy_test.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/formatted/k8s.go
  pkg/formatted/time.go
  pkg/printer/printer.go
  pkg/testutil/tekton.go
  vendor/github.com/hako/durafmt/.gitignore
  vendor/github.com/hako/durafmt/.travis.yml
  vendor/github.com/hako/durafmt/CODE_OF_CONDUCT.md
  vendor/github.com/hako/durafmt/CONTRIBUTING.md
  vendor/github.com/hako/durafmt/LICENSE
  vendor/github.com/hako/durafmt/README.md
  vendor/github.com/hako/durafmt/durafmt.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#27 Refactor test to utils and builder
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/task/list_test.go
  pkg/cmd/taskrun/list_test.go
  pkg/test/builder/doc.go
  pkg/test/builder/pipeline.go
  pkg/test/builder/pipelinerun.go
  pkg/test/builder/task.go
  pkg/test/builder/taskrun.go
  pkg/test/cobra.go
  pkg/test/params.go
  pkg/testutil/test_params.go
Labels: approved, cla: yes, lgtm, size/L

#28 Adding a gitignore file
  .gitignore
Labels: approved, cla: yes, lgtm, size/M

#33 fixes completion command help formatting
  pkg/cmd/completion/completion.go
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, size/M

#24 Shows pipelinerun logs
  pkg/cli/interface.go
  pkg/cli/params.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/root.go
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs.go
  pkg/flags/flags.go
  pkg/formatted/k8s.go
  pkg/logs/fakelog.go
  pkg/logs/logs.go
  pkg/test/builder/pod.go
  pkg/test/builder/taskrun.go
  pkg/test/params.go
Labels: approved, cla: yes, lgtm, size/XXL

#34 Refactoring params to use clientcmd to load the configuration file
  cmd/tkn/main.go
  go.mod
  go.sum
  pkg/cli/params.go
  pkg/flags/flags.go
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/README.md
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/mitchellh/go-homedir/homedir.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#36 Fixes command name and description inconsistency
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/taskrun/list.go
Labels: approved, cla: yes, lgtm, size/XS

#37 Add describe subcommand
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/pipeline.go
Labels: approved, cla: yes, lgtm, size/L

#39 Generate the zsh completion the same way kubectl is doing it
  pkg/cmd/completion/completion.go
Labels: approved, cla: yes, lgtm, size/L

#40 Proper OS exit status when a failure occures when listing
  cmd/tkn/main.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#41 Fix docs links from tektoncd/pipeline to tektoncd/cli
  .github/pull_request_template.md
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#43 Fix double spacing in the pipelinerun description
  pkg/cmd/pipelinerun/list.go
Labels: approved, cla: yes, lgtm, size/XS

#44 Refactor pipeline describe command
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#49 Fix namespace flag description
  pkg/flags/flags.go
Labels: approved, cla: yes, lgtm, size/XS

#50 Few lintings fixes
  pkg/cli/params.go
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/pipelinerun/logs.go
  pkg/logs/logs.go
Labels: approved, cla: yes, lgtm, size/S
