Repository tektoncd/cli, pull requests merged in 2019-06, with the labels that each got.

#51 Check errors in completion subcommand
  pkg/cmd/completion/completion.go
Labels: approved, cla: yes, lgtm, size/S

#54 Error out if invalid subcommands are passed root comamnds
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/task/task.go
  pkg/cmd/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/M

#52 Add logs subcommand for taskrun
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/logs_test.go
  pkg/cmd/taskrun/taskrun.go
  pkg/logs/fakelog.go
Labels: approved, cla: yes, lgtm, size/L

#55 Fix file headers to use Tekton instead of Knative in copyright
  cmd/tkn/main.go
  pkg/cli/interface.go
  pkg/cli/params.go
  pkg/cmd/completion/completion.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/root.go
  pkg/dummy_test.go
  pkg/flags/flags.go
  test/dummy_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#58 Fix test names
  pkg/cmd/pipelinerun/pipelinerun_test.go
  pkg/cmd/task/task_test.go
  pkg/cmd/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#60 Bump tektoncd/plumbing with latest fixes
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#67 Add odic auth support
  cmd/tkn/main.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#71 Add hrishin as owner of the CLI
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#72 Print message also in case of pipelinerun failure
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/logs.go
Labels: approved, cla: yes, lgtm, size/L

#70 Suggest commands if incorrect entered
  pkg/cli/help.go
  pkg/cmd/completion/completion.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/root.go
  pkg/cmd/root_test.go
  pkg/cmd/task/task.go
  pkg/cmd/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/L

#73 Add a teeny bit more about how to use the dev cli 🙆‍♀️
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#77 Add a goreleaser configuration file for the release
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/M

#74 Add taskname to pipelinerun desc
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#68 Add document for all the commands
  README.md
  docs/cmd/tkn_completion.md
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_describe.md
  docs/cmd/tkn_pipeline_list.md
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_describe.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_pipelinerun_logs.md
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_list.md
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_list.md
  docs/cmd/tkn_taskrun_logs.md
  docs/cmd/tkn_version.md
Labels: approved, cla: yes, lgtm, size/XL

#85 doc: final touch to prepare v0.1.0 release
  README.md
  tekton/release-pipeline-run.yml
Labels: approved, cla: yes, lgtm, size/M

#86 Use a name_template for archive names.
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#87 fixes raedme
  README.md
Labels: approved, cla: yes, lgtm, size/S

#91 goreleaser: add the version ldflags
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#92 goreleaser: add brew formula and fix ldflags
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/S

#94 Dont show empty serviceAccount
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#97 Backport goreleaser fix to release-v0.1.x branch
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/S

#100 Add zsh and bash completions when installing with homebrew
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/S

#104 Add mising double quote to .goreleaser.yml for brew section
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#101 Remove unused field in the pod struct
  pkg/helper/pods/pod.go
Labels: approved, cla: yes, lgtm, size/XS

#102 goreleaser: do not mark the release as draft
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#96 Shell completion on objects
  pkg/cmd/completion/bash_completion.go
  pkg/cmd/completion/completion.go
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, size/L

#109 Add completion on namespace and kubeconfig
  pkg/cmd/completion/bash_completion.go
  pkg/flags/flags.go
Labels: approved, cla: yes, lgtm, size/M

#113 Update README with latest release links…
  README.md
Labels: approved, cla: yes, lgtm, size/S

#114 minor: whitespace cleanup
  README.md
Labels: approved, cla: yes, lgtm, size/S

#115 Fix #112 brew formula pedantic warnings
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#79 Improve CLI E2E test
  test/e2e-common.sh
  test/e2e-tests.sh
  test/resources/output-pipelinerun.yaml
  test/resources/task-volume.yaml
Labels: approved, cla: yes, lgtm, size/L

#119 Add a test for version command
  pkg/cmd/version/version_test.go
Labels: approved, cla: yes, lgtm, size/M

#130 Templatize describe Pipelinerun
  pkg/cmd/pipelinerun/describe.go
Labels: approved, cla: yes, lgtm, size/L
