Repository tektoncd/cli, pull requests merged in 2019-11, with the labels that each got.

#435 Remove date from man pages
  cmd/docs/man_docs.go
  docs/man/man1/tkn-clustertask-delete.1
  docs/man/man1/tkn-clustertask-list.1
  docs/man/man1/tkn-clustertask.1
  docs/man/man1/tkn-completion.1
  docs/man/man1/tkn-condition-delete.1
  docs/man/man1/tkn-condition-list.1
  docs/man/man1/tkn-condition.1
  docs/man/man1/tkn-pipeline-delete.1
  docs/man/man1/tkn-pipeline-describe.1
  docs/man/man1/tkn-pipeline-list.1
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-pipeline.1
  docs/man/man1/tkn-pipelinerun-cancel.1
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-pipelinerun-describe.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-pipelinerun-logs.1
  docs/man/man1/tkn-pipelinerun.1
  docs/man/man1/tkn-resource-create.1
  docs/man/man1/tkn-resource-delete.1
  docs/man/man1/tkn-resource-describe.1
  docs/man/man1/tkn-resource-list.1
  docs/man/man1/tkn-resource.1
  docs/man/man1/tkn-task-delete.1
  docs/man/man1/tkn-task-describe.1
  docs/man/man1/tkn-task-list.1
  docs/man/man1/tkn-task-start.1
  docs/man/man1/tkn-task.1
  docs/man/man1/tkn-taskrun-cancel.1
  docs/man/man1/tkn-taskrun-delete.1
  docs/man/man1/tkn-taskrun-describe.1
  docs/man/man1/tkn-taskrun-list.1
  docs/man/man1/tkn-taskrun-logs.1
  docs/man/man1/tkn-taskrun.1
  docs/man/man1/tkn-version.1
  docs/man/man1/tkn.1
Labels: approved, cla: yes, lgtm, size/L

#434 Remove Unnecessary Space from Start Error Messages
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/helper/labels/mergelabels.go
  pkg/helper/params/mergeparams.go
Labels: approved, cla: yes, lgtm, size/S

#436 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#431 Add options test cases
  pkg/helper/options/options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#437 Adding Path Information to Windows Install Instructions
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#371 starts pipeline with new resource
  go.sum
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/resource_testUtil.go
Labels: approved, cla: yes, lgtm, size/XXL

#439 Show params in pipeline describe command
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#441 Add danielhelfand as OWNER 🐱
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#445 Fix brew install from tap
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#446 Update README to 0.5.0
  README.md
Labels: approved, cla: yes, lgtm, size/S

#443 Show param default value in task describe
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#447 Add release process documentation
  RELEASE_PROCESS.md
Labels: approved, cla: yes, lgtm, size/M

#449 Linting yamls with yamllint 🏷
  .goreleaser.yml
  .yamllint
  tekton/goreleaser.yml
  tekton/release-pipeline.yml
Labels: approved, cla: yes, lgtm, size/S

#452 Add cloudEvent resource support to start command
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/list.go
Labels: approved, cla: yes, lgtm, size/L

#457 Fix resource creation failure in case of multiple
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#450 Show Status of Steps with TaskRun Describe
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
  pkg/helper/validate/validate.go
  pkg/helper/validate/validate_test.go
Labels: approved, cla: yes, lgtm, size/L

#461 Update go.sum
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#462 Bump plumbing to latest changes 🔗
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#466 Fix interactive input params on pipeline start
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/M

#472 Include Operating System and tkn Version in Issue Template
  .github/issue-template.md
Labels: approved, cla: yes, lgtm, size/XS

#464 Add Installation instruction when compiling from source
  README.md
Labels: approved, cla: yes, lgtm, size/S

#474 Uses vendored deps while building the binary in Makefile
  Makefile
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#471 Add Check in PipelineRun Logs for if Condition Available
  pkg/cmd/pipelinerun/log_reader.go
Labels: approved, cla: yes, lgtm, size/S

#478 Adding Timeout to tkn task start
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
  pkg/cmd/taskrun/log_reader.go
  pkg/cmd/taskrun/logs_test.go
Labels: approved, cla: yes, lgtm, size/S

#469 Include TaskRun Failure Message in Logs
  go.sum
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/log_reader.go
  pkg/cmd/taskrun/logs_test.go
Labels: approved, cla: yes, lgtm, size/L

#484 Add a step into the RELEASE_PROCESS documentation
  RELEASE_PROCESS.md
Labels: approved, cla: yes, lgtm, size/XS

#483 Fix failure in case of array param having single value
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/helper/params/mergeparams.go
  pkg/helper/params/mergeparams_test.go
Labels: approved, cla: yes, lgtm, size/L

#485 Minor Edits to RELEASE_PROCESS.md
  RELEASE_PROCESS.md
Labels: approved, cla: yes, lgtm, size/S
