Repository tektoncd/cli, pull requests merged in 2019-09, with the labels that each got.

#260 Update thrift dep from apache to github
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#258 Rephrase deletion confirmation phrase
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: approved, cla: yes, lgtm, size/S

#257 Add delete all flag to task command
  docs/cmd/tkn_task_delete.md
  docs/man/man1/tkn-task-delete.1
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#214 Make the resource and param input interactively
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/logs_testutil.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#266 Add ZSH completion on delete commands
  pkg/cmd/clustertask/delete.go
  pkg/cmd/completion/completion.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/task/delete.go
  pkg/cmd/taskrun/delete.go
Labels: approved, cla: yes, lgtm, size/S

#269 Add version to release tarball
  .gitignore
  Makefile
  tekton/goreleaser.yml
Labels: approved, cla: yes, lgtm, size/S

#271 Fix mispell pipelinerune => pipelinerun
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/XS

#267 updates README to refer 0.3.0 release
  README.md
Labels: approved, cla: yes, lgtm, size/S

#273 Add chmouel as an OWNER 🎉
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#275 Adding Unit Tests for Sorting Prs and Trs
  pkg/helper/pipelinerun/sort/sort_pipelineruns_test.go
  pkg/helper/taskrun/sort/sort_taskruns_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#250 Uncapitalize error strings
  cmd/docs/generate.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/helper/pods/fake/stream.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#280 Remove the VERSION generation from goreleaser
  .gitignore
  tekton/goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#282 Add release script
  tekton/README.md
  tekton/release.sh
Labels: approved, cla: yes, lgtm, size/L

#284 Add zsh to Readme for completion option
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#283 Choose the first pipeline if only one available
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
Labels: approved, cla: yes, lgtm, size/M

#290 🎨 Add rainbow colouring of steps label
  pkg/cmd/pipelinerun/log_writer.go
  pkg/cmd/taskrun/log_writer.go
  pkg/formatted/color.go
  pkg/formatted/color_test.go
Labels: approved, cla: yes, lgtm, size/L

#292 Silence Usage When an Error Occurs
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#293 Update install instructions in readme to 0.3.1
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#301 E2E tests fixes
  Makefile
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#303 TaskRun Describe Command
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_describe.md
  docs/man/man1/tkn-taskrun-describe.1
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#304 Fix document typos
  docs/cmd/tkn_clustertask_delete.md
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_pipelinerun_describe.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_resource_delete.md
  docs/cmd/tkn_resource_describe.md
  docs/cmd/tkn_resource_list.md
  docs/cmd/tkn_taskrun_delete.md
  docs/cmd/tkn_taskrun_describe.md
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-clustertask-delete.1
  docs/man/man1/tkn-clustertask-list.1
  docs/man/man1/tkn-clustertask.1
  docs/man/man1/tkn-completion.1
  docs/man/man1/tkn-pipeline-delete.1
  docs/man/man1/tkn-pipeline-describe.1
  docs/man/man1/tkn-pipeline-list.1
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-pipeline.1
  docs/man/man1/tkn-pipelinerun-cancel.1
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-pipelinerun-describe.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-pipelinerun-logs.1
  docs/man/man1/tkn-pipelinerun.1
  docs/man/man1/tkn-resource-delete.1
  docs/man/man1/tkn-resource-describe.1
  docs/man/man1/tkn-resource-list.1
  docs/man/man1/tkn-resource.1
  docs/man/man1/tkn-task-delete.1
  docs/man/man1/tkn-task-list.1
  docs/man/man1/tkn-task.1
  docs/man/man1/tkn-taskrun-delete.1
  docs/man/man1/tkn-taskrun-describe.1
  docs/man/man1/tkn-taskrun-list.1
  docs/man/man1/tkn-taskrun-logs.1
  docs/man/man1/tkn-taskrun.1
  docs/man/man1/tkn-version.1
  docs/man/man1/tkn.1
  pkg/cmd/clustertask/delete.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/list.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#302 Fix interactive prompt with --last
  go.mod
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#281 Add canceling feature to taskrun command
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_cancel.md
  docs/man/man1/tkn-taskrun-cancel.1
  docs/man/man1/tkn-taskrun.1
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/cmd/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#294 Doc: Improve taskrun help example
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-taskrun-list.1
  pkg/cmd/taskrun/list.go
Labels: approved, cla: yes, lgtm, size/S

#307 Fix -n not working with pipeline logs
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/start.go
Labels: approved, cla: yes, lgtm, size/M

#309 Change Error Message from Task for No Tasks Found in Namespace
  pkg/cmd/task/list.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#321 Fix CI breakage due to changes in pipeline-0.7.0 release
  test/resources/output-pipelinerun.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#318 Fix the logs command when creating a pipelinerun
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#325 Adding missing copyright header
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/root_test.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/flags/flags_test.go
  pkg/formatted/k8s.go
  pkg/formatted/time.go
  pkg/helper/pods/pod_test.go
  pkg/test/builder/clustertask.go
  pkg/test/builder/doc.go
  pkg/test/builder/pipeline.go
  pkg/test/builder/pipelinerun.go
  pkg/test/builder/task.go
  pkg/test/builder/taskrun.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#327 Correct COPR Package Section README Typos
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#329 Align Pipeline Describe Output with Other Describe Commands
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#324 Align TaskRun Describe Output with Task Describe Output
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#331 Fix misspell in dummy test
  pkg/dummy_test.go
  test/dummy_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#328 Add Check to Taskrun Cancel for Already Executed Taskrun
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#316 Improve the error message on pipeline create
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#333 Add Check to PipelineRun Cancel for Already Executed PipelineRun
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#335 Add Vendored Dependencies to Spec
  tekton/rpmbuild/build.sh
  tekton/rpmbuild/tekton.spec
Labels: approved, cla: yes, lgtm, size/XXL

#336 Update templating to use `$(…)` instead of `${…}`
  tekton/goreleaser.yml
  tekton/release-pipeline.yml
Labels: approved, cla: yes, lgtm, size/S

#338 Update README to 0.4.0 release
  README.md
Labels: approved, cla: yes, lgtm, size/S

#337 Fix spec file path
  tekton/rpmbuild/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#323 Add task describe subcommand
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_describe.md
  docs/man/man1/tkn-task-describe.1
  docs/man/man1/tkn-task.1
  pkg/cmd/completion/completion.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/task.go
Labels: approved, cla: yes, lgtm, size/XL

#340 Cleanup -l flag across commands
  docs/cmd/tkn_pipeline_logs.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-taskrun-list.1
  go.mod
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
Labels: approved, cla: yes, lgtm, size/M
