Repository tektoncd/cli, pull requests merged in 2019-12, with the labels that each got.

#487 0.5.1 version in README
  README.md
Labels: approved, cla: yes, lgtm, size/M

#486 Improve message for creating new resource in start
  pkg/cmd/pipeline/start.go
Labels: approved, cla: yes, lgtm, size/XS

#495 Use serviceAccountName instead of serviceAccount
  test/resources/output-pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/XS

#493 Remove Extra Space from TaskRun Not Found Error
  pkg/cmd/taskrun/log_reader.go
  pkg/cmd/taskrun/logs_test.go
Labels: approved, cla: yes, lgtm, size/XS

#492 tkn pipeline create Command
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_create.md
  docs/man/man1/tkn-pipeline-create.1
  docs/man/man1/tkn-pipeline.1
  pkg/cli/interface.go
  pkg/cmd/pipeline/create.go
  pkg/cmd/pipeline/create_test.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/testdata/pipeline.yaml
  pkg/cmd/pipeline/testdata/pipelinerun.yaml
  pkg/helper/file/file.go
  pkg/helper/file/file_test.go
  pkg/helper/file/testdata/task.yaml
Labels: approved, cla: yes, lgtm, size/XL

#502 Add tkn task create
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_create.md
  docs/man/man1/tkn-task-create.1
  docs/man/man1/tkn-task.1
  pkg/cmd/task/create.go
  pkg/cmd/task/create_test.go
  pkg/cmd/task/task.go
  pkg/cmd/task/testdata/task.yaml
  pkg/cmd/task/testdata/taskrun.yaml
Labels: approved, cla: yes, lgtm, size/L

#506 Bump to tektoncd/pipeline 0.9.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#507 Add Namespace Check to Pipeline and Task Create Commands
  pkg/cmd/pipeline/create.go
  pkg/cmd/pipeline/create_test.go
  pkg/cmd/task/create.go
  pkg/cmd/task/create_test.go
Labels: approved, cla: yes, lgtm, size/S

#504 Add tkn resource create -f Option
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_resource_create.md
  docs/man/man1/tkn-resource-create.1
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/resource_testUtil.go
  pkg/cmd/pipelineresource/testdata/pipelineresource.yaml
  pkg/cmd/pipelineresource/testdata/pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/L

#509 Add NFPM (deb/rpm) release to goreleaser
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/S

#512 Fix input params are not respected
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start_test.go
  pkg/helper/params/mergeparams.go
Labels: approved, cla: yes, lgtm, size/S

#510 Debian package
  tekton/debbuild/README.md
  tekton/debbuild/container/Dockerfile
  tekton/debbuild/container/buildpackage.sh
  tekton/debbuild/control/changelog
  tekton/debbuild/control/compat
  tekton/debbuild/control/control
  tekton/debbuild/control/rules
  tekton/debbuild/control/source/format
  tekton/debbuild/run.sh
Labels: approved, cla: yes, lgtm, size/L

#513 Update Versions in README for 0.6.0
  README.md
Labels: approved, cla: yes, lgtm, size/S

#514 Add info in README about debian installs
  README.md
  RELEASE_PROCESS.md
Labels: approved, cla: yes, lgtm, size/M

#515 Change NFPM package name
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#516 Fix install bash and zsh completion
  tekton/debbuild/container/Dockerfile
  tekton/debbuild/container/buildpackage.sh
  tekton/debbuild/control/changelog
  tekton/debbuild/control/control
  tekton/debbuild/control/rules
Labels: approved, cla: yes, lgtm, size/S

#518 Add dep on Tektoncd Release 0.9.2
  go.mod
  go.sum
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pull_request_resource.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#517 Test for tkn task start --filename
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#528 Set default to False for Show Logs on TaskRun and PipelineRun
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/M

#533 Show Cancelled Instead of Failed for PipelineRun and TaskRun Describe
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_cancel.md
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_cancel.md
  docs/man/man1/tkn-pipelinerun-cancel.1
  docs/man/man1/tkn-taskrun-cancel.1
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/describe_test.go
  pkg/formatted/k8s.go
Labels: approved, cla: yes, lgtm, size/L

#536 Switch to gotest.tools/v3 instead of testify 🐺
  go.mod
  go.sum
  pkg/cmd/pipeline/logs_testutil.go
  pkg/cmd/pipelineresource/resource_testUtil.go
  pkg/helper/test/util.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/gotest.tools/v3/LICENSE
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/assert/result.go
  vendor/gotest.tools/v3/internal/difflib/LICENSE
  vendor/gotest.tools/v3/internal/difflib/difflib.go
  vendor/gotest.tools/v3/internal/format/diff.go
  vendor/gotest.tools/v3/internal/format/format.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#537 Use ./hack/tools.go instead of dummy_test.go ⚓
  go.mod
  go.sum
  hack/tools.go
  test/dummy_test.go
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#535 Bump github.com/imdario/mergo to 0.3.8
  go.mod
  go.sum
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/merge.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#538 Add piyush as an OWNER 🕺
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#547 Remove Namespace Check for Clustertask Commands
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#541 Add triggerbinding list
  README.md
  docs/cmd/tkn.md
  docs/cmd/tkn_triggerbinding.md
  docs/cmd/tkn_triggerbinding_list.md
  docs/man/man1/tkn-triggerbinding-list.1
  docs/man/man1/tkn-triggerbinding.1
  docs/man/man1/tkn.1
  pkg/cmd/root.go
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggerbinding/list_test.go
  pkg/cmd/triggerbinding/triggerbinding.go
  pkg/cmd/triggerbinding/triggerbinding_test.go
  pkg/test/builder/triggerbinding.go
Labels: approved, cla: yes, lgtm, size/XL

#551 Add eventlistener list
  README.md
  docs/cmd/tkn.md
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_list.md
  docs/man/man1/tkn-eventlistener-list.1
  docs/man/man1/tkn-eventlistener.1
  docs/man/man1/tkn.1
  pkg/cmd/eventlistener/eventlistener.go
  pkg/cmd/eventlistener/eventlistener_test.go
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/list_test.go
  pkg/cmd/root.go
  pkg/test/builder/eventlistener.go
Labels: approved, cla: yes, lgtm, size/XL

#540 Adds command to delete triggertemplate
  docs/cmd/tkn_triggertemplate.md
  docs/cmd/tkn_triggertemplate_delete.md
  docs/man/man1/tkn-triggertemplate-delete.1
  docs/man/man1/tkn-triggertemplate.1
  pkg/cmd/triggertemplate/delete.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/cmd/triggertemplate/triggertemplate.go
Labels: approved, cla: yes, lgtm, size/L

#552 Converting TaskRun Describe Tests to Use Test Builder Methods for StepState
  pkg/cmd/taskrun/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#555 change test name
  pkg/cmd/triggertemplate/delete_test.go
Labels: approved, cla: yes, lgtm, size/XS

#554 Add command to delete triggerbinding
  docs/cmd/tkn_triggerbinding.md
  docs/cmd/tkn_triggerbinding_delete.md
  docs/man/man1/tkn-triggerbinding-delete.1
  docs/man/man1/tkn-triggerbinding.1
  go.mod
  go.sum
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggerbinding/triggerbinding.go
Labels: approved, cla: yes, lgtm, size/L

#558 Bump hashicorp/golang-lru
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_test.go
  vendor/github.com/hashicorp/golang-lru/go.mod
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
