Repository tektoncd/cli, pull requests merged in 2019-10, with the labels that each got.

#343 Add information about docs and checks for github pr template
  .github/pull_request_template.md
Labels: approved, cla: yes, lgtm, size/XS

#344 Add a check if we have generated the docs on PR
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#342 Allow passing labels to start
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/M

#348 Update the new brew location
  .goreleaser.yml
  README.md
Labels: approved, cla: yes, lgtm, size/S

#349 Check if Namespace Exists for Task List Command
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/test/cobra.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#352 Set namespace in e2e tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#353 Bump tektoncd/plumbing dependency ⛽️
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#350 Add Namespace Check to Task Delete Command
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/list.go
  pkg/helper/validate/validate.go
  pkg/helper/validate/validate_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#354 Fix unit tests
  pkg/cmd/pipelineresource/resource_testUtil.go
Labels: approved, cla: yes, lgtm, size/XS

#355 Add Namespace Check for Task Describe Command
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#358 Fixes test increase timeout for expect
  pkg/cmd/pipelineresource/resource_testUtil.go
Labels: approved, cla: yes, lgtm, size/XS

#360 Add Namespace Check to TaskRun Describe Command
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#356 Don't show just Error if container came back only with "Error"
  pkg/helper/pods/container.go
Labels: approved, cla: yes, lgtm, size/XS

#359 Add Namespace Check to Taskrun List Command
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#357 Add tkn condition to README
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#363 Use *** instead of plain text for password
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
Labels: approved, cla: yes, lgtm, size/S

#365 Refactor NamespaceExists
  pkg/cli/interface.go
  pkg/cli/params.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/list.go
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/list.go
  pkg/helper/validate/validate.go
  pkg/helper/validate/validate_test.go
  pkg/test/params.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#367 removes complexity of read timeout from test
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/resource_testUtil.go
Labels: approved, cla: yes, lgtm, size/M

#373 Add Namespace Check to Taskrun Delete Command
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#375 Add Namespace Check to TaskRun Logs Command
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/logs_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#374 Add Namespace Check to TaskRun Cancel Command
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#376 Fix panic on pipeline logs
  pkg/cmd/pipelinerun/log_reader.go
  pkg/helper/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/S

#379 Change for release and tagging
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#378 Add namespace Check to Pipeline List Command
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/logs.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#389 Add Namespace Check to Condition List Command
  pkg/cmd/condition/list.go
  pkg/cmd/condition/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#387 Add Namespace Check to Pipeline Logs Command
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#388 Add Namespace Check to Clustertask Commands
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#382 Add Namespace Check to Pipeline Delete Command
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#385 Add Namespace Check to Pipeline Describe Command
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#392 Add Namespace Check to Resource List Command
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#384 Use targetURI for cloudEvent resource details
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
Labels: approved, cla: yes, lgtm, size/S

#396 Add Namespace Check to Resource Create Command
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#399 Add Namespace Check to Condition Delete Command
  pkg/cmd/condition/delete.go
  pkg/cmd/condition/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#398 Generate windows binary release files as zip file
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#393 Add Namespace Check to Resource Delete Command
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#406 Remove 386 and arm archs
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#409 Add Namespace Check to PipelineRun Describe Command
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#395 Add Namespace Check to Resource Describe Command
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#408 Add Namespace Check to PipelineRun Delete Command
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#411 Add Namespace Check to PipelineRun Logs Command
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/pipelinerun/logs.go
Labels: approved, cla: yes, lgtm, size/L

#410 Add Namespace Check to PipelineRun Cancel Command
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#407 Add Namespace Check to PipelineRun List Command
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#415 Add Namespace Check to Task Start Command
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#416 Add Namespace Check to Pipeline Start Command
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#417 Clean Up Pipeline Start Test and Correct Task Start Namespace Check
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#420 Add installation instructions for Win to README kind/feature
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#423 Fix make lint warning
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/logs_testutil.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/resource_testUtil.go
Labels: approved, cla: yes, lgtm, size/M

#425 Make sure we are in the right directory when launching the tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#426 Enable golint
  .golangci.yml
  Makefile
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S
