Repository tektoncd/cli, pull requests merged in 2019-08, with the labels that each got.

#194 Bugfix Returns an error if no pipelines found
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/logs.go
Labels: approved, cla: yes, lgtm, size/M

#185 Add Limit Option for PipelineRuns
  docs/cmd/tkn_pipelinerun_list.md
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/flags/flags.go
Labels: approved, cla: yes, lgtm, size/M

#198 Improve pipeline logs command
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/log_reader.go
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/pipelinerun/logs.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#187 Add multiple service accounts for pipeline start
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_logs.md
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-clustertask-list.1
  docs/man/man1/tkn-clustertask.1
  docs/man/man1/tkn-completion.1
  docs/man/man1/tkn-pipeline-describe.1
  docs/man/man1/tkn-pipeline-list.1
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-pipeline.1
  docs/man/man1/tkn-pipelinerun-describe.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-pipelinerun-logs.1
  docs/man/man1/tkn-pipelinerun.1
  docs/man/man1/tkn-resource-describe.1
  docs/man/man1/tkn-resource-list.1
  docs/man/man1/tkn-resource.1
  docs/man/man1/tkn-task-list.1
  docs/man/man1/tkn-task.1
  docs/man/man1/tkn-taskrun-list.1
  docs/man/man1/tkn-taskrun-logs.1
  docs/man/man1/tkn-taskrun.1
  docs/man/man1/tkn-version.1
  docs/man/man1/tkn.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#205 Fix nil pointer error
  pkg/cmd/clustertask/list.go
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/task/list.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
  pkg/formatted/k8s.go
  pkg/formatted/time.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#206 Fix follow mode for interactive pipeline logs
  pkg/cmd/pipeline/logs.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#207 Add support for a `--build-cross-tests` flag in presubmit
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#208 Fix missing link to clustertask command in README
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#213 Change `pr` to `tr` in taskrun doc
  docs/cmd/tkn_taskrun_list.md
  pkg/cmd/taskrun/list.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#211 Adds verification to number of args for completion cmd
  pkg/cmd/completion/completion.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#215 fix(): release link from cli to pipelines repo
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#216 updates readme download instructions
  README.md
  tekton/release-pipeline-run.yml
Labels: approved, cla: yes, lgtm, size/S

#212 Add Limit Option for TaskRuns
  docs/cmd/tkn_task_list.md
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#219 Add cancelling the pipelinerun feature
  docs/cmd/tkn_pipeline_logs.md
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_cancel.md
  docs/cmd/tkn_task_list.md
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-pipelinerun-cancel.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-pipelinerun.1
  docs/man/man1/tkn-taskrun-list.1
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/pipelinerun.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#226 Fixes show sub commands help section
  pkg/cmd/clustertask/list.go
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/task/list.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/logs.go
Labels: approved, cla: yes, lgtm, size/M

#218 Add the information regarding docs
  DEVELOPMENT.md
  docs/cmd/tkn_pipeline_logs.md
  docs/cmd/tkn_pipelinerun_logs.md
  docs/cmd/tkn_taskrun_logs.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#230 Fix homebrew formula test
  .goreleaser.yml
Labels: approved, cla: yes, lgtm, size/XS

#234 fixes pipeline logs command with --last flag
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/logs.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#239 Display sub commands types only if there is any.
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, size/S

#240 Add delete for bash completion
  pkg/cmd/completion/completion.go
Labels: approved, cla: yes, lgtm, size/XS

#246 Add force delete flag to deleting resource
  docs/cmd/tkn_resource_delete.md
  docs/man/man1/tkn-resource-delete.1
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#253 Add delete for clustertask command
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_delete.md
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#249 Print command tips after starting pipeline
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#252 Mock github API calls
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
Labels: approved, cla: yes, lgtm, size/L

#251 Add yaml lint makefile target
  .yamllint
  Makefile
  test/resources/output-pipelinerun.yaml
  test/resources/task-volume.yaml
Labels: approved, cla: yes, lgtm, size/M

#254 Refactor TaskRun and PipelineRun Sorting
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/taskrun/list.go
  pkg/helper/pipelinerun/sort/sort_pipelineruns.go
  pkg/helper/taskrun/sort/sort_taskruns.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
