Repository tektoncd/cli, pull requests merged in 2020-01, with the labels that each got.

#564 Add Command to Remove EventListener
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_delete.md
  docs/man/man1/tkn-eventlistener-delete.1
  docs/man/man1/tkn-eventlistener.1
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/eventlistener/eventlistener.go
Labels: approved, cla: yes, lgtm, size/L

#556 Error Message for Using --last with tkn task start -f
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#521 Refactoring pipeline log tests
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/task/logs_test.go
  pkg/helper/options/logs_test.go
  test/prompt/prompt.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#566 Updating Release Notes for tkn
  RELEASE_PROCESS.md
  tekton/README.md
  tekton/rpmbuild/README.md
  tekton/rpmbuild/rpmbuild-run.yml
Labels: approved, cla: yes, lgtm, size/L

#567 Add Chocolatey Package to README and Other Minor Edits
  README.md
Labels: approved, cla: yes, lgtm, size/S

#568 Refactor triggertemplate list test
  pkg/cmd/triggertemplate/list_test.go
Labels: approved, cla: yes, lgtm, size/L

#569 Syncronize cobra to latest
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/pflag/.travis.yml
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool_slice.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/duration_slice.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/float32_slice.go
  vendor/github.com/spf13/pflag/float64_slice.go
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/spf13/pflag/int32_slice.go
  vendor/github.com/spf13/pflag/int64_slice.go
  vendor/github.com/spf13/pflag/int_slice.go
  vendor/github.com/spf13/pflag/ip_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/github.com/spf13/pflag/string_slice.go
  vendor/github.com/spf13/pflag/string_to_int64.go
  vendor/github.com/spf13/pflag/uint_slice.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#577 Update all delete commands to support multiple arguments
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_delete.md
  docs/cmd/tkn_condition_delete.md
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_delete.md
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_delete.md
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_resource_delete.md
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_delete.md
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_delete.md
  docs/cmd/tkn_triggerbinding.md
  docs/cmd/tkn_triggerbinding_delete.md
  docs/cmd/tkn_triggertemplate.md
  docs/cmd/tkn_triggertemplate_delete.md
  docs/man/man1/tkn-clustertask-delete.1
  docs/man/man1/tkn-condition-delete.1
  docs/man/man1/tkn-eventlistener-delete.1
  docs/man/man1/tkn-pipeline-delete.1
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-resource-delete.1
  docs/man/man1/tkn-task-delete.1
  docs/man/man1/tkn-taskrun-delete.1
  docs/man/man1/tkn-triggerbinding-delete.1
  docs/man/man1/tkn-triggertemplate-delete.1
  go.mod
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/condition/delete.go
  pkg/cmd/condition/delete_test.go
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/helper/names/formats.go
  pkg/helper/options/delete.go
  pkg/helper/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/XL

#580 Refactoring pipeline start tests.
  pkg/cmd/pipeline/logs_testutil.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#583 Add tkn task start -f With Remote Files
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  go.sum
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, size/S

#585 Refactor delete command code to be a bit more DRY
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/condition/delete.go
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/task/delete.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggertemplate/delete.go
  pkg/helper/deleter/deleter.go
  pkg/helper/deleter/deleter_test.go
Labels: approved, cla: yes, lgtm, size/L

#586 Add nil Check for PipelineRun Desc TaskRun Sorting
  go.sum
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
Labels: approved, cla: yes, lgtm, size/L

#590 Add coloured status condition
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
Labels: approved, cla: yes, lgtm, size/M

#595 Add colouring for steps status 🎨
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
  pkg/helper/validate/validate.go
Labels: approved, cla: yes, lgtm, size/S

#597 Correct tkn task start Typo
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, size/XS

#600 Remove Second TaskRun from tkn pr desc Test
  pkg/cmd/pipelinerun/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#592 Subtle cosmetics changes to task describe
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
  pkg/formatted/color.go
  pkg/formatted/color_test.go
Labels: approved, cla: yes, lgtm, size/XL

#607 Fix release tarball version to remove the v at first
  tekton/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#610 Add Namespace to tkn pipeline desc
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#582 tkn create Command Proposal
  docs/cmd/tkn.md
  docs/cmd/tkn_create.md
  docs/man/man1/tkn-create.1
  docs/man/man1/tkn.1
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, size/L

#614 Do not show bracket when showing the RunAfter.Tasks in Pipeline desc
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#613 Set no colours automatically when not running with a tty or a pipe
  go.mod
  pkg/flags/flags.go
Labels: approved, cla: yes, lgtm, size/S

#616 Skipping flaky interactive tests 🧨
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/task/logs_test.go
Labels: approved, cla: yes, lgtm, size/M

#611 Generate steps name when none has been provided
  pkg/cmd/task/describe.go
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
Labels: approved, cla: yes, lgtm, size/M

#622 Add tests for k8.Condition
  pkg/formatted/k8s_test.go
Labels: approved, cla: yes, lgtm, size/M

#624 Add tkn clustertask describe Command
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_describe.md
  docs/man/man1/tkn-clustertask-describe.1
  docs/man/man1/tkn-clustertask.1
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_missing_param_default_one_of_everything.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_with_name_only.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_full_clustertask_multiple_taskruns.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_with_no_arguments.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Failure_from_listing_taskruns.golden
  pkg/cmd/task/describe_test.go
Labels: approved, cla: yes, lgtm, size/XL

#620 Add emojis to pipeline/pipelinerun/task/taskrun describe
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/task/describe.go
  pkg/cmd/taskrun/describe.go
  pkg/formatted/color.go
  pkg/formatted/color_test.go
Labels: approved, cla: yes, lgtm, size/M

#633 Add emojis support for tkn clustertask describe command
  pkg/cmd/clustertask/describe.go
Labels: approved, cla: yes, lgtm, size/S

#635 Return error inspite of nil
  pkg/cmd/pipeline/logs.go
Labels: approved, cla: yes, lgtm, size/XS

#641 Implement output for pipeline describe
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#591 Sort Steps for tkn taskrun desc by StartedAt
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
Labels: approved, cla: yes, lgtm, size/L

#608 Add flag to task and pipeline to only delete related resources
  docs/cmd/tkn_pipeline_delete.md
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_task_delete.md
  docs/cmd/tkn_taskrun_delete.md
  docs/man/man1/tkn-pipeline-delete.1
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-task-delete.1
  docs/man/man1/tkn-taskrun-delete.1
  pkg/cmd/clustertask/delete.go
  pkg/cmd/condition/delete.go
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggertemplate/delete.go
  pkg/helper/deleter/deleter.go
  pkg/helper/deleter/deleter_test.go
  pkg/helper/options/delete.go
  pkg/helper/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#650 Remove 🏻 from the step emoji 🍲
  pkg/formatted/color.go
  pkg/formatted/color_test.go
Labels: approved, cla: yes, lgtm, size/XS

#643 --dry-run Option for tkn pipeline start
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  go.sum
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#653 Minor wording fixes on the RELEASE_PROCESS document
  RELEASE_PROCESS.md
Labels: approved, cla: yes, lgtm, size/S

#656 Use gotest.tools assert package instead of testify 🍵
  go.mod
  go.sum
  pkg/cmd/version/version_test.go
  pkg/flags/flags_test.go
  pkg/formatted/color_test.go
  pkg/formatted/k8s_test.go
  pkg/helper/file/file_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#657 Refactor --dry-run Tests for tkn pipeline start To Use Golden File
  go.sum
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json.golden
Labels: approved, cla: yes, lgtm, size/L

#661 Fix output=name for pipelinerun list
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_output_as_name.golden
Labels: approved, cla: yes, lgtm, size/S

#665 Fix workspace not getting copied with --last
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/S

#644 Fix bug always overriding GenerateName when specifying last flag
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#636 Remove repeated sentence.
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#669 Remove tkn create
  docs/cmd/tkn.md
  docs/man/man1/tkn.1
  pkg/cmd/create/create.go
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, size/M
