Repository tektoncd/cli, pull requests merged in 2020-10, with the labels that each got.

#1196 Update OSX instruction to install from brew 🍻
  README.md
Labels: approved, lgtm, release-note, size/XS

#1197 Reorganize Release Process Docs and Add Details
  RELEASE_PROCESS.md
  tekton/README.md
  tekton/rpmbuild/README.md
Labels: approved, lgtm, release-note-none, size/M

#1192 Add EventListener Logs Command
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_logs.md
  docs/cmd/tkn_taskrun_logs.md
  docs/man/man1/tkn-eventlistener-logs.1
  docs/man/man1/tkn-eventlistener.1
  pkg/cmd/eventlistener/eventlistener.go
  pkg/cmd/eventlistener/logs.go
  pkg/cmd/eventlistener/logs_test.go
  pkg/cmd/taskrun/logs.go
  pkg/options/logs.go
  test/e2e-tests.sh
  test/e2e/eventListener/eventListener_test.go
  test/resources/eventlistener.yaml
  test/resources/eventlistener/eventlistener-multi-replica.yaml
  test/resources/eventlistener/eventlistener.yaml
Labels: approved, lgtm, release-note, size/XL

#1201 Avoid Use of Previous TaskRunSpecStatus and PipelineRunSpecStatus with Start Commands
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start_test.go
  pkg/options/start.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#1205 Remove Assertions to Help with Debugging EventListener e2e Failures
  go.mod
  test/e2e/eventListener/eventListener_test.go
  test/helper/helper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/append_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/format_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/group_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/sort_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_test.go
  third_party/VENDOR-LICENSE/gotest.tools/LICENSE
  third_party/VENDOR-LICENSE/gotest.tools/internal/difflib/LICENSE
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/assert/assert.go
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/cmp/result.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/internal/difflib/LICENSE
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/format/diff.go
  vendor/gotest.tools/internal/format/format.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/XXL

#1207 tkn pr describe failing in pr with conditions
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_multiple_taskrun_without_status.golden
  pkg/pipelinerun/description/description.go
Labels: approved, lgtm, release-note, size/L

#1208 Common Way of Referring to Tekton Resources in User Facing Messages: EventListener
  docs/cmd/tkn.md
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_delete.md
  docs/cmd/tkn_eventlistener_describe.md
  docs/cmd/tkn_eventlistener_list.md
  docs/cmd/tkn_eventlistener_logs.md
  docs/man/man1/tkn-eventlistener-list.1
  docs/man/man1/tkn-eventlistener.1
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/eventlistener.go
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_InvalidNamespace.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_NonExistedName.golden
Labels: approved, lgtm, release-note, size/M

#1211 Common Way of Referring to Tekton Resources in User Facing Messages: TriggerBinding
  docs/cmd/tkn.md
  docs/cmd/tkn_triggerbinding.md
  docs/cmd/tkn_triggerbinding_delete.md
  docs/cmd/tkn_triggerbinding_describe.md
  docs/cmd/tkn_triggerbinding_list.md
  docs/man/man1/tkn-triggerbinding-delete.1
  docs/man/man1/tkn-triggerbinding-describe.1
  docs/man/man1/tkn-triggerbinding-list.1
  docs/man/man1/tkn-triggerbinding.1
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggerbinding/describe.go
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggerbinding/testdata/TestListTriggerBinding-Invalid_namespace.golden
  pkg/cmd/triggerbinding/testdata/TestListTriggerBinding-No_TriggerBinding.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_Invalid_Namespace.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_NonExistedName.golden
  pkg/cmd/triggerbinding/triggerbinding.go
Labels: approved, lgtm, release-note, size/M

#1215 Update readme for 0.13.1 and fix lint task
  README.md
  tekton/release-pipeline.yml
Labels: approved, lgtm, release-note-none, size/M

#1210 Common Way of Referring to Tekton Resources in User Facing Messages: ClusterTriggerBinding
  docs/cmd/tkn.md
  docs/cmd/tkn_clustertriggerbinding.md
  docs/cmd/tkn_clustertriggerbinding_delete.md
  docs/cmd/tkn_clustertriggerbinding_describe.md
  docs/cmd/tkn_clustertriggerbinding_list.md
  docs/man/man1/tkn-clustertriggerbinding-delete.1
  docs/man/man1/tkn-clustertriggerbinding-describe.1
  docs/man/man1/tkn-clustertriggerbinding-list.1
  docs/man/man1/tkn-clustertriggerbinding.1
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
  pkg/cmd/clustertriggerbinding/delete.go
  pkg/cmd/clustertriggerbinding/describe.go
  pkg/cmd/clustertriggerbinding/list.go
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_NonExistedName.golden
  pkg/cmd/clustertriggerbinding/testdata/TestListClusterTriggerBinding-No_ClusterTriggerBindings.golden
Labels: approved, lgtm, release-note, size/M

#1209 Common Way of Referring to Tekton Resources in User Facing Messages: Condition
  docs/cmd/tkn.md
  docs/cmd/tkn_condition.md
  docs/cmd/tkn_condition_delete.md
  docs/cmd/tkn_condition_describe.md
  docs/cmd/tkn_condition_list.md
  docs/man/man1/tkn-condition-delete.1
  docs/man/man1/tkn-condition-list.1
  docs/man/man1/tkn-condition.1
  pkg/cmd/condition/condition.go
  pkg/cmd/condition/delete.go
  pkg/cmd/condition/describe.go
  pkg/cmd/condition/list.go
  pkg/cmd/condition/testdata/TestConditionDescribe-invalid_condition_name.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-invalid_namespace.golden
  pkg/cmd/condition/testdata/TestConditionList-Failed_to_list_condition_resources.golden
  pkg/cmd/condition/testdata/TestConditionList-Failed_to_list_condition_resources_with_specify_output_flag.golden
Labels: approved, lgtm, release-note, size/M

#1213 Common Way of Referring to Tekton Resources in User Facing Messages: TriggerTemplate
  docs/cmd/tkn.md
  docs/cmd/tkn_triggertemplate.md
  docs/cmd/tkn_triggertemplate_delete.md
  docs/cmd/tkn_triggertemplate_describe.md
  docs/cmd/tkn_triggertemplate_list.md
  docs/man/man1/tkn-triggertemplate-delete.1
  docs/man/man1/tkn-triggertemplate-describe.1
  docs/man/man1/tkn-triggertemplate-list.1
  docs/man/man1/tkn-triggertemplate.1
  pkg/cmd/triggertemplate/delete.go
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/list.go
  pkg/cmd/triggertemplate/testdata/TestListTriggerTemplate-Invalid_namespace.golden
  pkg/cmd/triggertemplate/testdata/TestListTriggerTemplate-No_TriggerTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_Invalid_Namespace.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NonExistedName.golden
  pkg/cmd/triggertemplate/triggertemplate.go
Labels: approved, lgtm, release-note, size/M

#1214 Fix unit test failures with go 1.15
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start_test.go
  pkg/formatted/color_test.go
  pkg/test/helpers.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/M

#1217 Fix Alignment of Usage
  pkg/cmd/root.go
Labels: approved, lgtm, release-note, size/XS

#1218 Document NO_COLOR and Edit README Headers
  README.md
Labels: approved, lgtm, release-note-none, size/M

#1221 Updates Hub Dependency
  docs/cmd/tkn_hub_get.md
  docs/cmd/tkn_hub_get_pipeline.md
  docs/cmd/tkn_hub_get_task.md
  docs/man/man1/tkn-hub-get-pipeline.1
  docs/man/man1/tkn-hub-get-task.1
  go.mod
  go.sum
  vendor/github.com/tektoncd/hub/api/gen/http/resource/client/encode_decode.go
  vendor/github.com/tektoncd/hub/api/gen/http/resource/client/types.go
  vendor/github.com/tektoncd/hub/api/gen/resource/client.go
  vendor/github.com/tektoncd/hub/api/gen/resource/endpoints.go
  vendor/github.com/tektoncd/hub/api/gen/resource/service.go
  vendor/github.com/tektoncd/hub/api/gen/resource/views/view.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/get/get.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/formatter/field.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/search.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL
