Repository tektoncd/cli, pull requests merged in 2020-07, with the labels that each got.

#1040 Common Way of Referring to Tekton Resources for User Facing Messages: PipelineRun
  docs/cmd/tkn.md
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_cancel.md
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_pipelinerun_describe.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_pipelinerun_logs.md
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-pipelinerun-describe.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-pipelinerun-logs.1
  docs/man/man1/tkn-pipelinerun.1
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertriggerbinding/delete_test.go
  pkg/cmd/condition/delete_test.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_negative_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-no_mixing_pipelinename_and_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-limit_pipelineruns_negative_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-no_mixing_pipelinename_and_label.golden
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/deleter/deleter.go
Labels: approved, lgtm, size/L

#1043 Change kn to tkn in Feature Issue Template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: approved, lgtm, size/XS

#1041 Update the pull_request_template for release-note 📖
  .github/pull_request_template.md
Labels: approved, lgtm, size/S

#1058 Bump to use tektoncd/triggers v0.6.0
  go.mod
  go.sum
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OutputYAMLWithMultipleBindingAndInterceptors.golden
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/triggers/test/buffer.go
  vendor/github.com/tektoncd/triggers/test/builder/eventlistener.go
  vendor/github.com/tektoncd/triggers/test/e2e-tests-ingress.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1059 Enables auto selection of task for `describe` command if only one task is present
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_WithoutNameIfOnlyOneTaskPresent.golden
  pkg/cmd/task/testdata/TestTaskDescribe_WithoutNameIfOnlyOneV1beta1TaskPresent.golden
Labels: approved, lgtm, release-note, size/L

#1063 Fix pipelinerun logs error
  pkg/cmd/pipelinerun/logs_test.go
  pkg/log/pipeline_reader.go
Labels: approved, lgtm, release-note, size/S

#1036 Add --use-param-defaults option for tkn task start
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/options/start.go
  test/e2e/task/start_test.go
  test/resources/read-file.yaml
Labels: approved, lgtm, release-note, size/L

#1073 Bump to tektoncd/pipeline v0.14.2
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/go.mod
  third_party/VENDOR-LICENSE/vendor/golang.org/x/crypto/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/net/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/text/LICENSE
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/paths.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1071 panic when there are no TR/PR present in the namespace while using (--last) option with (describe)
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1075 Add the misspell linter, and fix some misspellings.
  .golangci.yml
  pkg/formatted/param.go
  pkg/pods/container_test.go
  test/e2e/build_templates.go
  test/e2e/pipeline/pipeline_test.go
Labels: approved, lgtm, release-note-none, size/S

#1078 Add deadcode to golangci-lint
  .golangci.yml
Labels: approved, lgtm, release-note-none, size/XS

#1066 Support VolumeClaimTemplates with --workspace for tkn start Commands
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
  pkg/file/file.go
  pkg/workspaces/testdata/pvc-typo.yaml
  pkg/workspaces/testdata/pvc.yaml
  pkg/workspaces/workspaces.go
  pkg/workspaces/workspaces_test.go
  test/e2e/cli.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/task/start_test.go
  test/resources/pipeline-with-workspace.yaml
  test/resources/pvc.yaml
  test/resources/task-with-workspace.yaml
Labels: approved, lgtm, release-note, size/L

#1077 adds finally logs in pipelinerun
  pkg/cmd/pipelinerun/logs_test.go
  pkg/log/pipeline_reader.go
  pkg/pipelinerun/tracker.go
  pkg/pipelinerun/tracker_test.go
  test/e2e/helper.go
  test/e2e/pipelinerun/pipelinerun_test.go
  test/resources/pipelinerun-with-finally.yaml
Labels: approved, lgtm, release-note, size/XL

#1081 Update Version Param for golang-build Task
  tekton/release-pipeline.yml
Labels: approved, lgtm, release-note, size/XS

#1082 correct catalog task golangci lint path
  tekton/release.sh
Labels: approved, lgtm, release-note, size/XS

#1084 update version in readme
  README.md
Labels: approved, lgtm, release-note, size/M

#1044 Reorganise cli E2E folder structure
  test/builder/builder.go
  test/builder/sort.go
  test/builder/validate.go
  test/cli/cli.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/pipeline/start_test.go
  test/e2e/pipelinerun/pipelinerun_test.go
  test/e2e/resource/create_test.go
  test/e2e/task/start_test.go
  test/framework/clients.go
  test/framework/helper.go
  test/framework/logs.go
  test/helper/helper.go
  test/wait/helper-wait.go
  test/wait/wait.go
Labels: approved, lgtm, size/XL

#1051 ClusterTask start interactive mode
  docs/cmd/tkn_clustertask_start.md
  docs/man/man1/tkn-clustertask-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_no_output.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_output=json.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_--timeout_v1beta1.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_no_output.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_no_output_v1beta1.golden
  pkg/options/start.go
  test/builder/builder.go
  test/e2e/clustertask/start_test.go
  test/framework/clients.go
  test/resources/read-file-clustertask.yaml
Labels: approved, lgtm, release-note, size/XL
