Repository tektoncd/cli, pull requests merged in 2020-02, with the labels that each got.

#662 Add --dry-run Option for tkn task start
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
Labels: approved, cla: yes, lgtm, size/L

#663 Add --dry-run Option for tkn ct start
  docs/cmd/tkn_clustertask_start.md
  docs/man/man1/tkn-clustertask-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_no_output.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_output=json.golden
Labels: approved, cla: yes, lgtm, size/L

#670 Fix overriding GenerateName on taskrun
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#673 Update gotest.tools to use our fork
  go.mod
  go.sum
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/golden/golden.go
  vendor/gotest.tools/v3/internal/difflib/difflib.go
  vendor/gotest.tools/v3/internal/format/format.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#674 Update readme for 0.7.1 release
  README.md
Labels: approved, cla: yes, lgtm, size/M

#678 Bump gotest.tools/v3 dep to 3.0.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#609 Start doing testing against pipeline release nightly
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#676 --all option for tkn taskrun delete
  docs/cmd/tkn_taskrun_delete.md
  docs/man/man1/tkn-taskrun-delete.1
  pkg/cmd/clustertask/delete.go
  pkg/cmd/condition/delete.go
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/task/delete.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggertemplate/delete.go
  pkg/helper/options/delete.go
  pkg/helper/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#682 Add flag --use-pipelinerun to start the rerun with a specific pr
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/helper/pipelinerun/pipelinerun.go
Labels: approved, cla: yes, lgtm, size/L

#677 Improve release docs
  RELEASE_PROCESS.md
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/S

#692 Add tkn cluster delete --all
  docs/cmd/tkn_clustertask_delete.md
  docs/man/man1/tkn-clustertask-delete.1
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/helper/options/delete.go
  pkg/helper/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#694 Add --step flag for taskrun logs
  docs/cmd/tkn_pipelinerun_logs.md
  docs/cmd/tkn_taskrun_logs.md
  docs/man/man1/tkn-pipelinerun-logs.1
  docs/man/man1/tkn-taskrun-logs.1
  pkg/cmd/pipelinerun/log_test.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/taskrun/log_reader.go
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/logs_test.go
  pkg/helper/options/logs.go
Labels: approved, cla: yes, lgtm, size/L

#699 --all option for tkn el delete
  docs/cmd/tkn_eventlistener_delete.md
  docs/man/man1/tkn-eventlistener-delete.1
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/eventlistener/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#697 --all option for tkn resource delete
  docs/cmd/tkn_resource_delete.md
  docs/man/man1/tkn-resource-delete.1
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#698 --all option for tkn condition delete
  docs/cmd/tkn_condition_delete.md
  docs/man/man1/tkn-condition-delete.1
  pkg/cmd/condition/delete.go
  pkg/cmd/condition/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#691 Fix bug about Complete logs not shown for failed TaskRun
  pkg/cmd/taskrun/log_reader.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#689 --all option for tkn pipelinerun delete
  docs/cmd/tkn_pipelinerun_delete.md
  docs/man/man1/tkn-pipelinerun-delete.1
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#700 Shows --- for empty values on "DEFAULT VALUES" column
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_missing_param_default_one_of_everything.golden
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/testdata/TestPipelinesDescribe_with_multiple_resource_param_task_run.golden
  pkg/cmd/task/describe.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  pkg/cmd/task/testdata/TestTaskDescribe_OnlyNameParams.golden
Labels: approved, cla: yes, lgtm, size/S

#703 Add pipeline version information
  pkg/cmd/root.go
  pkg/cmd/version/testdata/TestVersionGood.golden
  pkg/cmd/version/testdata/TestVersionGood/test-available-new-version.golden
  pkg/cmd/version/testdata/TestVersionGood/test-same-version.golden
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
  pkg/helper/version/version.go
Labels: approved, cla: yes, lgtm, size/M

#705 --all option for tkn triggertemplate delete
  docs/cmd/tkn_triggertemplate_delete.md
  docs/man/man1/tkn-triggertemplate-delete.1
  pkg/cmd/triggertemplate/delete.go
  pkg/cmd/triggertemplate/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#711 Fix help command
  pkg/cmd/root.go
Labels: approved, cla: yes, lgtm, size/XS

#704 --all option for tkn triggerbinding delete
  docs/cmd/tkn_triggerbinding_delete.md
  docs/man/man1/tkn-triggerbinding-delete.1
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggerbinding/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#707 Add --last to `tkn pr logs`
  docs/cmd/tkn_pipelinerun_logs.md
  docs/man/man1/tkn-pipelinerun-logs.1
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/pipelinerun/logs_test.go
Labels: approved, cla: yes, lgtm, size/L

#721 nil Check for lr.Stream for TaskRun Logs
  pkg/cmd/taskrun/log_reader.go
Labels: approved, cla: yes, lgtm, size/XS

#727 Fix typo
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#719 --prefix-name option for tkn pipeline start
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#729 Add Warning for --all Flags for Pipeline and Task Delete
  pkg/cmd/pipeline/delete.go
  pkg/cmd/task/delete.go
Labels: approved, cla: yes, lgtm, size/S

#740 Update golangci-lint target 🍵
  Makefile
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#741 Adds timeout to pipeline start
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json.golden
Labels: approved, cla: yes, lgtm, size/S

#709 Refactoring log writer.
  pkg/cmd/pipelinerun/log_reader.go
  pkg/cmd/pipelinerun/log_writer.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/taskrun/log_reader.go
  pkg/cmd/taskrun/logs.go
  pkg/helper/log/log.go
  pkg/helper/log/writer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#714 Add --use-taskrun for taskrun
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#747 Show Sidecar Names with tkn tr desc
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_cancel_taskrun.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_empty_taskrun.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_failed.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_no_resourceref.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_no_taskref.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_only_taskrun.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_default.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_pending_one_sidecar.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_running_multiple_sidecars.golden
  pkg/formatted/color.go
  pkg/formatted/color_test.go
  pkg/helper/taskrun/description/taskrun_description.go
Labels: approved, cla: yes, lgtm, size/M

#753 Add Warning Message for tkn task start --timeout
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, size/XS

#749 Refactoring log reader.
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/logs_test.go
  pkg/helper/log/pipeline_reader.go
  pkg/helper/log/reader.go
  pkg/helper/log/task_reader.go
  pkg/helper/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/L

#724 --prefix-name option for tkn task start
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/L

#745 Add Error Message for Deletion When No Args or --all Flag Specified
  go.sum
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/condition/delete_test.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/helper/options/delete.go
  pkg/helper/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#755 Remove trigger alias for start subcommands 🚉
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, size/S

#757 Pin the go version in the release pipeline 🖊
  tekton/release-pipeline.yml
Labels: approved, cla: yes, lgtm, size/XS

#758 Use -mod=vendor during the release 👼
  tekton/release-pipeline.yml
Labels: approved, cla: yes, lgtm, size/XS

#754 A little Refactoring log reader.
  pkg/helper/log/pipeline_reader.go
Labels: approved, cla: yes, lgtm, size/S

#761 Improve --keep Description and Unit Tests for Prompts
  docs/cmd/tkn_pipelinerun_delete.md
  docs/man/man1/tkn-pipelinerun-delete.1
  pkg/cmd/pipelinerun/delete.go
  pkg/helper/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/S

#759 Add support for yubikey in debbuild 🦌
  tekton/debbuild/container/Dockerfile
  tekton/debbuild/container/buildpackage.sh
  tekton/debbuild/run.sh
Labels: approved, cla: yes, lgtm, size/M
