Repository tektoncd/cli, pull requests merged in 2020-03, with the labels that each got.

#762 Update README for v0.8.0
  README.md
Labels: approved, cla: yes, lgtm, size/M

#751 cleanup (task/start) Remove -t timeout shorthand from tkn task start
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#768 Remove the name param in cluster resource creation
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
Labels: approved, cla: yes, lgtm, size/M

#774 Fix several typos
  pkg/cmd/pipeline/create.go
  pkg/cmd/pipeline/create_test.go
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/task/create.go
  pkg/cmd/task/create_test.go
  pkg/cmd/task/start.go
  pkg/file/file_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#779 Change timeout to string for tkn task start
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
Labels: approved, cla: yes, lgtm, size/S

#780 Use text/template Instead of html/template for PipelineRun Describe
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_cancelled_pipelinerun.golden
  pkg/pipelinerun/description/description.go
Labels: approved, cla: yes, lgtm, size/S

#781 Fix SIGSEGV on pipelinerun logs
  pkg/cmd/pipelinerun/logs_test.go
  pkg/log/pipeline_reader.go
Labels: approved, cla: yes, lgtm, size/L

#770 Add tkn official image on contrib 🖌
  contrib/tkn-image/Dockerfile
  contrib/tkn-image/README.md
Labels: approved, cla: yes, lgtm, size/S

#788 Add Sidecar Status to tkn taskrun describe
  go.sum
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_sidecar_status_defaults_and_failures.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_pending_one_sidecar.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_running_multiple_sidecars.golden
  pkg/taskrun/description/taskrun_description.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, cla: yes, lgtm, size/L

#773 Convert --all to Delete all Pipelines/Tasks in Namespace
  docs/cmd/tkn_pipeline_delete.md
  docs/cmd/tkn_task_delete.md
  docs/man/man1/tkn-pipeline-delete.1
  docs/man/man1/tkn-task-delete.1
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/options/delete.go
  pkg/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#789 Add flag to --reverse list taskruns/pipelineruns
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-taskrun-list.1
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_in_reverse.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_in_reverse_with_output_flag.golden
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/testdata/TestListTaskRuns-print_in_reverse.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns-print_in_reverse_with_output_flag.golden
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#505 Improve CLI e2e go tests
  go.mod
  test/README.md
  test/dummy_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/build_logs.go
  test/e2e/build_templates.go
  test/e2e/clients.go
  test/e2e/helper.go
  test/e2e/helper_interactive.go
  test/e2e/helper_wait.go
  test/e2e/init_test.go
  test/e2e/pipeline_e2e_test.go
  test/e2e/tkn_helper_utility.go
  test/e2e/validate.go
  test/e2e/wait.go
  test/environment/environment.go
  test/resources/output-pipelinerun.yaml
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/gotest.tools/v3/icmd/command.go
  vendor/gotest.tools/v3/icmd/exitcode.go
  vendor/gotest.tools/v3/icmd/ops.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#792 Update Triggers dependency for CLI
  go.mod
  go.sum
  vendor/github.com/tektoncd/triggers/pkg/client/dynamic/clientset/clientset.go
  vendor/github.com/tektoncd/triggers/pkg/client/dynamic/clientset/errorclient.go
  vendor/github.com/tektoncd/triggers/pkg/client/dynamic/clientset/tekton/tekton.go
  vendor/github.com/tektoncd/triggers/test/controller.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#797 Bump to tektoncd/pipeline 0.11.0-rc2
  go.mod
  go.sum
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f.golden
  third_party/VENDOR-LICENSE/contrib.go.opencensus.io/exporter/ocagent/LICENSE
  third_party/VENDOR-LICENSE/github.com/PuerkitoBio/purell/LICENSE
  third_party/VENDOR-LICENSE/github.com/PuerkitoBio/urlesc/LICENSE
  third_party/VENDOR-LICENSE/github.com/emicklei/go-restful/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-openapi/jsonpointer/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-openapi/jsonreference/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-openapi/spec/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-openapi/swag/LICENSE
  third_party/VENDOR-LICENSE/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/mailru/easyjson/LICENSE
  third_party/VENDOR-LICENSE/github.com/openzipkin/zipkin-go/model/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/cli-runtime/pkg/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/kube-openapi/pkg/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/utils/LICENSE
  third_party/VENDOR-LICENSE/sigs.k8s.io/kustomize/pkg/LICENSE
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/condition_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/workspace/validate.go
  vendor/github.com/tektoncd/pipeline/test/builder/condition.go
  vendor/github.com/tektoncd/pipeline/test/builder/pipeline.go
  vendor/github.com/tektoncd/pipeline/test/builder/task.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#803 Change PipelineRuns to TaskRuns for tkn tr delete --keep Description
  docs/cmd/tkn_taskrun_delete.md
  docs/man/man1/tkn-taskrun-delete.1
  pkg/cmd/taskrun/delete.go
Labels: approved, cla: yes, lgtm, size/XS

#795 Change Status Check for PipelineRun and TaskRun Cancel for Color Formatting
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/formatted/k8s.go
Labels: approved, cla: yes, lgtm, size/M

#787 Add description to task, clustertask, condition list
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/clustertask/testdata/TestClusterTaskListOnlyClusterTasks.golden
  pkg/cmd/condition/list.go
  pkg/cmd/condition/list_test.go
  pkg/cmd/condition/testdata/TestConditionList-Found_conditions.golden
  pkg/cmd/condition/testdata/TestConditionList-Specify_output_flag.golden
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks.golden
  pkg/formatted/description.go
  pkg/formatted/description_test.go
  test/e2e/build_templates.go
Labels: approved, cla: yes, lgtm, size/L

#796 Build tkn binary before running cli tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#805 Add description to describe command
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_missing_param_default_one_of_everything.golden
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelinesDescribe_with_multiple_resource_param_task_run.golden
  pkg/cmd/pipeline/testdata/TestPipelinesDescribe_with_resource_param_task_run.golden
  pkg/cmd/pipeline/testdata/TestPipelinesDescribe_with_task_run.golden
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceDescribe_WithParams.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceDescribe_WithSecretParams.golden
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  test/e2e/build_templates.go
Labels: approved, cla: yes, lgtm, size/M

#809 Change TaskRun and PipelineRun Sorting from sort.Slice to sort.Sort
  go.sum
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/taskrun/list.go
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/sort/by_start_time.go
  pkg/pipelinerun/sort/by_start_time_test.go
  pkg/taskrun/list/list.go
  pkg/taskrun/sort/by_start_time.go
  pkg/taskrun/sort/by_start_time_test.go
  test/e2e/build_templates.go
Labels: approved, cla: yes, lgtm, size/L

#815 Remove Duplicate Error Message When Deleting Nonexistent Resource
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/condition/delete_test.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/deleter/deleter.go
  pkg/deleter/deleter_test.go
Labels: approved, cla: yes, lgtm, size/L

#818 Add license to e2e tests
  test/dummy_test.go
  test/e2e/build_logs.go
  test/e2e/build_templates.go
  test/e2e/clients.go
  test/e2e/helper.go
  test/e2e/helper_interactive.go
  test/e2e/helper_wait.go
  test/e2e/init_test.go
  test/e2e/pipeline_e2e_test.go
  test/e2e/tkn_helper_utility.go
  test/e2e/validate.go
  test/e2e/wait.go
  test/environment/environment.go
Labels: approved, cla: yes, lgtm, size/L

#810 Refactor task list cmd with v1beta1 support
  pkg/cli/interface.go
  pkg/cli/params.go
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/list/list.go
  pkg/test/dynamic/clientset/clientset.go
  pkg/test/dynamic/clientset/errorclient.go
  pkg/test/dynamic/clientset/tekton.go
  pkg/test/dynamic/dynamictestclinet.go
  pkg/test/params.go
Labels: approved, cla: yes, lgtm, size/L

#821 Add Warning Message in v0.9.0 about tkn clustertask --timeout
  pkg/cmd/clustertask/start.go
Labels: approved, cla: yes, lgtm, size/XS

#812 Start PipelineRun from Local or Remote File
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename.golden
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, size/L

#825 Add v1beta1 support for clustertask list
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/clustertask/testdata/TestClusterTaskListOnlyClusterTasksv1alpha1.golden
  pkg/cmd/clustertask/testdata/TestClusterTaskListOnlyClusterTasksv1beta1.golden
  pkg/cmd/task/list.go
  pkg/list/list.go
Labels: approved, cla: yes, lgtm, size/L

#823 Adds test for list v1beta1
  pkg/cmd/task/list_test.go
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_v1beta1.golden
Labels: approved, cla: yes, lgtm, size/M

#833 Fix Test Failure from go v1.14.0 Update
  pkg/file/file_test.go
Labels: approved, cla: yes, lgtm, size/XS

#832 v1beta1 support for pipeline list cmd
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/testdata/TestPipelineList_only_pipelines_v1beta1.golden
  pkg/cmd/taskrun/list.go
  pkg/pipeline/pipeline.go
  pkg/taskrun/list/list.go
  pkg/test/builder/unstructured.go
Labels: approved, cla: yes, lgtm, size/L

#836 Add RELEASE_VERSION build-arg to the image 📟
  contrib/tkn-image/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#837 v1beta1 support for taskrun delete
  pkg/actions/delete/delete.go
  pkg/actions/gvr.go
  pkg/actions/list/list.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/task/list.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/pipeline/pipeline.go
  pkg/taskrun/list/list.go
Labels: approved, cla: yes, lgtm, size/L

#841 v1beta1 support for pipelinerun list & delete cmd
  pkg/actions/delete/delete.go
  pkg/actions/gvr.go
  pkg/actions/list/list.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-Invalid_namespace.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-all_in_namespace.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-by_output_as_name.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-by_pipeline_name.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-by_template.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-filter_pipelineruns_by_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-filter_pipelineruns_by_label_with_in_query.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-limit_pipelineruns_greater_than_maximum_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-limit_pipelineruns_negative_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-limit_pipelineruns_returned_to_1.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-limit_pipelineruns_with_output_flag_set.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-no_mixing_pipelinename_and_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-print_in_reverse.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-print_in_reverse_with_output_flag.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns_v1beta1-print_pipelineruns_in_all_namespaces.golden
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/pipelinerun/sort/by_namespace.go
  pkg/pipelinerun/sort/by_namespace_test.go
  pkg/pipelinerun/sort/by_start_time.go
  pkg/pipelinerun/sort/by_start_time_test.go
  pkg/test/builder/unstructured.go
Labels: approved, cla: yes, lgtm, size/XXL

#846 Sort resources in start subcommands 🌮
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: approved, area/testing, cla: yes, kind/cleanup, lgtm, size/XS

#835 Add ROADMAP.md 🤖
  README.md
  ROADMAP.md
Labels: approved, area/roadmap, cla: yes, lgtm, size/M

#826 Add workspace option to pipeline start
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  docs/reference/cmd/pipeline_start.md
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/workspaces/workspaces.go
  pkg/workspaces/workspaces_test.go
Labels: approved, cla: yes, lgtm, size/L

#847 Fix tkn pipeline version issue
  pkg/cmd/version/version.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, cla: yes, lgtm, size/L

#849 remove redundant code
  pkg/workspaces/workspaces.go
  pkg/workspaces/workspaces_test.go
Labels: approved, cla: yes, lgtm, size/S

#848 v1beta1 support for task delete command
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs_test.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/task/task.go
  pkg/taskrun/list/list_test.go
  pkg/test/builder/apiresource.go
Labels: approved, cla: yes, lgtm, size/XL

#852 v1beta1 support for pipeline delete command
  pkg/actions/delete/delete.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#854 Add workspace option to task start
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-start.1
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, cla: yes, lgtm, size/M

#829 Clustertriggerbinding List Command
  docs/cmd/tkn.md
  docs/cmd/tkn_clustertriggerbinding.md
  docs/cmd/tkn_clustertriggerbinding_list.md
  docs/man/man1/tkn-clustertriggerbinding-list.1
  docs/man/man1/tkn-clustertriggerbinding.1
  docs/man/man1/tkn.1
  go.sum
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
  pkg/cmd/clustertriggerbinding/list.go
  pkg/cmd/clustertriggerbinding/list_test.go
  pkg/cmd/clustertriggerbinding/testdata/TestListClusterTriggerBinding-By_output_as_name.golden
  pkg/cmd/clustertriggerbinding/testdata/TestListClusterTriggerBinding-Multiple_ClusterTriggerBindings.golden
  pkg/cmd/clustertriggerbinding/testdata/TestListClusterTriggerBinding-Multiple_ClusterTriggerBindings_with_output_format.golden
  pkg/cmd/clustertriggerbinding/testdata/TestListClusterTriggerBinding-No_ClusterTriggerBindings.golden
  pkg/cmd/root.go
  pkg/test/builder/clustertriggerbinding.go
Labels: approved, cla: yes, lgtm, size/XL
