Repository tektoncd/cli, pull requests merged in 2020-04, with the labels that each got.

#856 Add tkn clustertriggerbinding delete command
  docs/cmd/tkn_clustertriggerbinding.md
  docs/cmd/tkn_clustertriggerbinding_delete.md
  docs/man/man1/tkn-clustertriggerbinding-delete.1
  docs/man/man1/tkn-clustertriggerbinding.1
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
  pkg/cmd/clustertriggerbinding/delete.go
  pkg/cmd/clustertriggerbinding/delete_test.go
Labels: approved, cla: yes, lgtm, size/L

#844 Add s390x target to Makefile
  .goreleaser.yml
  Makefile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#853 v1beta1 support for clustertask delete
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/list.go
Labels: approved, cla: yes, lgtm, size/L

#857 fix typo and change function name
  pkg/actions/list/list.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/task/list.go
  pkg/pipeline/pipeline.go
  pkg/pipelinerun/pipelinerun.go
  pkg/task/task.go
  pkg/taskrun/list/list.go
Labels: approved, cla: yes, lgtm, size/M

#855 Import docs/README.md from website
  docs/README.md
Labels: approved, cla: yes, lgtm, size/L

#822 Warning Messages About Removing create -f
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_resource_create.md
  docs/cmd/tkn_task.md
  docs/man/man1/tkn-pipeline.1
  docs/man/man1/tkn-resource-create.1
  docs/man/man1/tkn-task.1
  pkg/cmd/pipeline/create.go
  pkg/cmd/pipeline/create_test.go
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/task/create.go
  pkg/cmd/task/create_test.go
Labels: approved, cla: yes, lgtm, size/S

#864 Add pradeepitm12 to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#866 v1beta1 support for pipeline and run logs command
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/log/pipeline_reader.go
  pkg/log/task_reader.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/pipelinelastrun.go
  pkg/pipelinerun/pipelinerun.go
  pkg/taskrun/taskrun.go
  pkg/test/dynamic/dynamictestclinet.go
Labels: approved, cla: yes, lgtm, size/XXL

#873 v1beta1 support for taskrun cancel
  pkg/actions/update/update.go
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/taskrun/update.go
  pkg/test/dynamic/dynamictestclinet.go
Labels: approved, cla: yes, lgtm, size/L

#870 Bump task describe command to v1beta1
  pkg/actions/delete.go
  pkg/actions/get.go
  pkg/actions/list.go
  pkg/actions/update.go
  pkg/actions/watch.go
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/list.go
  pkg/cmd/task/logs.go
  pkg/cmd/task/testdata/TestTaskV1beta1Describe_Full.golden
  pkg/cmd/taskrun/delete.go
  pkg/pipeline/pipeline.go
  pkg/pipelinerun/pipelinerun.go
  pkg/task/task.go
  pkg/taskrun/get.go
  pkg/taskrun/list/list.go
  pkg/taskrun/update.go
  pkg/taskrun/watch.go
  pkg/test/builder/unstructured.go
  pkg/test/helpers.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/clustertask/clustertask.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/clustertask/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/pipeline/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/pipeline/pipeline.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/pipelinerun/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/pipelinerun/pipelinerun.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/task/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/task/task.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/taskrun/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1beta1/taskrun/taskrun.go
  vendor/github.com/tektoncd/pipeline/test/README.md
  vendor/github.com/tektoncd/pipeline/test/adoc.go
  vendor/github.com/tektoncd/pipeline/test/build_logs.go
  vendor/github.com/tektoncd/pipeline/test/clients.go
  vendor/github.com/tektoncd/pipeline/test/columns.txt
  vendor/github.com/tektoncd/pipeline/test/controller.go
  vendor/github.com/tektoncd/pipeline/test/e2e-common.sh
  vendor/github.com/tektoncd/pipeline/test/e2e-tests-upgrade.sh
  vendor/github.com/tektoncd/pipeline/test/e2e-tests-yaml.sh
  vendor/github.com/tektoncd/pipeline/test/e2e-tests.sh
  vendor/github.com/tektoncd/pipeline/test/markdown-lint-config.rc
  vendor/github.com/tektoncd/pipeline/test/presubmit-tests.sh
  vendor/github.com/tektoncd/pipeline/test/secret.go
  vendor/github.com/tektoncd/pipeline/test/wait.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#877 Bump tektoncd/triggers to v0.4.0
  go.mod
  go.sum
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/cluster_trigger_binding_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_template_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#878 fix tasrun cancel command
  pkg/actions/patch.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/taskrun/patch.go
Labels: approved, cla: yes, lgtm, size/M

#880 v1beta1 support for pipelinerun cancel
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/pipelinerun/pipelinerun.go
  pkg/taskrun/get.go
Labels: approved, cla: yes, lgtm, size/L

#828 Properly Capture APIVersion when Starting Task or Pipeline with --dry-run
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_no_output_v1beta1.golden
  pkg/cmd/pipeline/create_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename_v1alpha1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/pipeline/testdata/pipeline-v1alpha1.yaml
  pkg/cmd/pipeline/testdata/pipeline-v1beta1.yaml
  pkg/cmd/pipeline/testdata/pipelinerun.yaml
  pkg/cmd/task/create_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/testdata/task-v1alpha1.yaml
  pkg/cmd/task/testdata/task-v1beta1.yaml
  pkg/cmd/task/testdata/taskrun.yaml
Labels: approved, cla: yes, lgtm, size/XL

#883 use List from task pkg
  pkg/cmd/task/list.go
Labels: approved, cla: yes, lgtm, size/S

#885 Refactoring in make file
  Makefile
Labels: approved, cla: yes, lgtm, size/S

#881 Sort TaskRuns by Start Time for tkn task describe
  pkg/cmd/task/describe.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  pkg/cmd/task/testdata/TestTaskV1beta1Describe_Full.golden
Labels: approved, cla: yes, lgtm, size/XS

#892 Sort TaskRuns by Start Time for Clustertask Describe
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_full_clustertask_multiple_taskruns.golden
Labels: approved, cla: yes, lgtm, size/XS

#891 Bump pipeline desc to v1beta1
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_empty.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_run.golden
  pkg/log/pipeline_reader.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
Labels: approved, cla: yes, lgtm, size/XL

#894 Sort PipelineRuns by Start Time for Pipeline Describe
  go.sum
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_multiple_v1alpha1_pipelineruns.golden
Labels: approved, cla: yes, lgtm, size/L

#896 Bump pipelinerun describe to v1beta1
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribeV1beta1.golden
  pkg/log/pipeline_reader.go
  pkg/pipelinerun/description/description.go
  pkg/pipelinerun/description/description_test.go
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#887 Update Release Process Docs on Updating Plumbing tkn Images
  RELEASE_PROCESS.md
Labels: approved, cla: yes, lgtm, size/XS

#899 Fix e2e on pipeline 0.10
  test/e2e/build_templates.go
  test/e2e/clients.go
  test/e2e/helper_wait.go
  test/e2e/sort.go
  test/e2e/wait.go
Labels: approved, cla: yes, lgtm, size/M

#897 Add test for task package
  pkg/clustertask/clustertask.go
  pkg/clustertask/clustertask_test.go
  pkg/cmd/clustertask/describe.go
  pkg/cmd/task/describe.go
  pkg/task/task.go
  pkg/task/task_test.go
Labels: approved, cla: yes, lgtm, size/L

#889 Flag to start a Pipeline without prompting for default value
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/params/mergeparams.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#898 Fix lint error and handle properly
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/resource_testUtil.go
  pkg/formatted/color.go
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#901 Remove Default Timeout of 1h for Pipeline and Task start
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename_v1alpha1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/start.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
Labels: approved, cla: yes, lgtm, size/M

#904 Set client version in the Debian package
  tekton/debbuild/container/buildpackage.sh
  tekton/debbuild/control/rules
Labels: approved, cla: yes, lgtm, size/S

#905 Modified param flag description
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#907 chore: fix typo inavlid > invalid
  pkg/cmd/pipeline/start.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#908 Bump tektoncd/pipeline to v0.11.2
  go.mod
  go.sum
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#884 Bump taskrun describe to v1beta1
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunWithSpecDescribe_custom_timeout.golden
  pkg/log/task_reader.go
  pkg/task/task.go
  pkg/taskrun/description/description.go
  pkg/taskrun/description/description_test.go
  pkg/taskrun/get.go
  pkg/taskrun/get_test.go
  pkg/taskrun/sort/by_namespace.go
  pkg/taskrun/sort/by_namespace_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, cla: yes, lgtm, size/XL

#893 Sort TaskRuns based on StartTime before deletion with keep
  pkg/cmd/taskrun/delete.go
Labels: approved, cla: yes, lgtm, size/XS

#910 Check Status of TaskRun for tkn pipelinerun describe
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribeV1beta1_taskrun_with_no_status.golden
  pkg/pipelinerun/description/description.go
Labels: approved, cla: yes, lgtm, size/L

#913 Corrects `logs` command to validate `--limit` option's value if it is <=0
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/logs_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#919 Disable colouring and emojis on windows
  pkg/flags/flags.go
Labels: approved, cla: yes, lgtm, size/XS

#912 Add tkn triggerbinding describe command
  docs/cmd/tkn_triggerbinding.md
  docs/cmd/tkn_triggerbinding_describe.md
  docs/man/man1/tkn-triggerbinding-describe.1
  docs/man/man1/tkn-triggerbinding.1
  pkg/cmd/triggerbinding/describe.go
  pkg/cmd/triggerbinding/describe_test.go
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_Empty.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_Invalid_Namespace.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_NoParams.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_NonExistedName.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithMultipleParams.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithOutputName.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithOutputYaml.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithParams.golden
  pkg/cmd/triggerbinding/triggerbinding.go
Labels: approved, cla: yes, lgtm, size/XL

#921 Fix --keep Description and Remove Need to use with --all Flag
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_taskrun_delete.md
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-taskrun-delete.1
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/options/delete.go
  pkg/options/delete_test.go
Labels: approved, cla: yes, lgtm, size/M

#922 fix aliases for clustertriggerbindings
  docs/cmd/tkn_clustertriggerbinding.md
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
Labels: approved, cla: yes, lgtm, size/XS

#923 Add tkn clustertriggerbinding describe command
  docs/cmd/tkn_clustertriggerbinding.md
  docs/cmd/tkn_clustertriggerbinding_describe.md
  docs/man/man1/tkn-clustertriggerbinding-describe.1
  docs/man/man1/tkn-clustertriggerbinding.1
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
  pkg/cmd/clustertriggerbinding/describe.go
  pkg/cmd/clustertriggerbinding/describe_test.go
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_Empty.golden
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_NoParams.golden
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_NonExistedName.golden
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_WithMultipleParams.golden
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_WithOutputName.golden
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_WithOutputYaml.golden
  pkg/cmd/clustertriggerbinding/testdata/TestTriggerBindingDescribe_WithParams.golden
Labels: approved, cla: yes, lgtm, size/L

#924 Bump pipeline start to v1beta1
  pkg/clustertask/clustertask_test.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_using_--filename.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/task/start_test.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs_test.go
  pkg/params/mergeparams.go
  pkg/params/mergeparams_test.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/pipelinelastrun.go
  pkg/pipeline/pipelinelastrun_test.go
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/task/task_test.go
  pkg/taskrun/get_test.go
  pkg/taskrun/list/list_test.go
  pkg/workspaces/workspaces.go
  pkg/workspaces/workspaces_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#917 little refactor for consistency
  pkg/actions/create.go
  pkg/cmd/task/start.go
  pkg/taskrun/create.go
  pkg/taskrun/get.go
  pkg/taskrun/patch.go
  pkg/taskrun/taskrun.go
  pkg/taskrun/watch.go
Labels: approved, cla: yes, lgtm, size/M

#928 Add tkn triggertemplate describe command
  docs/cmd/tkn_triggertemplate.md
  docs/cmd/tkn_triggertemplate_describe.md
  docs/man/man1/tkn-triggertemplate-describe.1
  docs/man/man1/tkn-triggertemplate.1
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/describe_test.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_Empty.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_InvalidResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_Invalid_Namespace.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NoParams.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NonExistedName.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_ParamsToResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleParams.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOneParam.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOutputName.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOutputYaml.golden
  pkg/cmd/triggertemplate/triggertemplate.go
  pkg/validate/validate.go
Labels: approved, cla: yes, lgtm, size/XL

#932 Fix Alignment of Output Resource TYPE Column for task desc
  pkg/cmd/task/describe.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  pkg/cmd/task/testdata/TestTaskV1beta1Describe_Full.golden
Labels: approved, lgtm, size/XS

#934 Implement convertDown function for Taskrun
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json_-f.golden
  pkg/pipelinerun/pipelinerun.go
  pkg/task/task.go
  pkg/taskrun/create.go
Labels: approved, lgtm, size/L

#930 Add params description to describe commands
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_missing_param_default_one_of_everything.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_full_clustertask_multiple_taskruns.golden
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_multiple_v1alpha1_pipelineruns.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_resource_param_run.golden
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  pkg/cmd/task/testdata/TestTaskDescribe_OnlyNameParams.golden
  pkg/cmd/task/testdata/TestTaskV1beta1Describe_Full.golden
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_InvalidResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_ParamsToResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleParams.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleResourceTemplate.golden
  test/e2e/build_templates.go
Labels: approved, lgtm, size/L

#937 Fix --dry-run with --filename Tests for All Start Commands
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json_-f_v1alpha1.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_using_--filename_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_output=json_-f_v1beta1.golden
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json_-f_v1beta1.golden
Labels: approved, lgtm, size/XL

#936 Bump tektoncd/pipeline to v0.11.3
  go.mod
  go.sum
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/param_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resultref.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/resources/apply.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/taskrun/resources/apply.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#926 Fix pipeline version not working
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, cla: yes, lgtm, size/M

#842 Build and publish tkn image on release 📌
  tekton/get-version.yaml
  tekton/goreleaser.yml
  tekton/publish.yaml
  tekton/release-pipeline.yml
Labels: approved, cla: yes, lgtm, size/L

#939 Add description command for condition
  docs/cmd/tkn_condition.md
  docs/cmd/tkn_condition_describe.md
  docs/man/man1/tkn-condition-describe.1
  docs/man/man1/tkn-condition.1
  pkg/cmd/condition/condition.go
  pkg/cmd/condition/describe.go
  pkg/cmd/condition/describe_test.go
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_command_and_arg.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_command_and_arg_with_output.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_script.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_script_with_output.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_with_one_resource_param.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_without_resource_param.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-invalid_condition_name.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-invalid_namespace.golden
  pkg/formatted/color.go
  pkg/formatted/color_test.go
Labels: approved, lgtm, size/XL

#933 Add eventlistener describe command
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_describe.md
  docs/man/man1/tkn-eventlistener-describe.1
  docs/man/man1/tkn-eventlistener.1
  go.mod
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/describe_test.go
  pkg/cmd/eventlistener/eventlistener.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_InvalidNamespace.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_NoArgProvided.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_NonExistedName.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithMultipleTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithOneClusterTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithOneTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_TwoTriggers.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithCELInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithMinRequiredField.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithMultipleBindingAndInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithOutputStatusURLAndName.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithWebhookInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithWebhookInterceptorsWithParams.golden
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NonExistedName.golden
Labels: approved, lgtm, size/XL

#941 Update template for EventListener Describe command
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithMultipleTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithOneClusterTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithOneTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_TwoTriggers.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithCELInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithMultipleBindingAndInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithOutputStatusURLAndName.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithWebhookInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithWebhookInterceptorsWithParams.golden
Labels: approved, lgtm, size/L

#938 Enable auto selection of the task for `logs` command if only one task is present.
  pkg/cmd/task/logs.go
  pkg/cmd/task/logs_test.go
Labels: approved, lgtm, ok-to-test, size/M

#942 Fix Description Typo and Add Test with Output Option for tkn el desc
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_eventlistener_describe.md
  docs/man/man1/tkn-eventlistener-describe.1
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/describe_test.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OutputYAMLWithMultipleBindingAndInterceptors.golden
Labels: approved, lgtm, size/L

#943 Remove namespace flag from clusterwide cmd's
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_delete.md
  docs/cmd/tkn_clustertask_describe.md
  docs/cmd/tkn_clustertask_list.md
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_clustertriggerbinding.md
  docs/cmd/tkn_clustertriggerbinding_delete.md
  docs/cmd/tkn_clustertriggerbinding_describe.md
  docs/cmd/tkn_clustertriggerbinding_list.md
  docs/man/man1/tkn-clustertask-delete.1
  docs/man/man1/tkn-clustertask-describe.1
  docs/man/man1/tkn-clustertask-list.1
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-clustertask.1
  docs/man/man1/tkn-clustertriggerbinding-delete.1
  docs/man/man1/tkn-clustertriggerbinding-describe.1
  docs/man/man1/tkn-clustertriggerbinding-list.1
  docs/man/man1/tkn-clustertriggerbinding.1
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
Labels: approved, lgtm, size/M

#944 Add flag to skip check flag in version cmd
  pkg/cmd/version/version.go
Labels: approved, lgtm, size/XS

#945 Fix release script and yaml
  tekton/release-pipeline-run.yml
  tekton/release-pipeline.yml
  tekton/release.sh
Labels: approved, lgtm, size/S

#946 Update readme for release 0.9.0
  README.md
Labels: approved, lgtm, size/M

#948 Fix dockerfile of debbuild
  tekton/debbuild/container/Dockerfile
Labels: approved, lgtm, size/XS
