Repository tektoncd/cli, pull requests merged in 2020-06, with the labels that each got.

#1002 Add `--trs` flag in `tkn ct delete` command
  docs/cmd/tkn_clustertask_delete.md
  docs/man/man1/tkn-clustertask-delete.1
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
Labels: approved, lgtm, ok-to-test, size/L

#977 Modified TriggerTemplate describe command for ResourceTemplates
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/describe_test.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_InvalidResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NoParams.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_ParamsToResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleParams.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOneParam.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOutputYaml.golden
Labels: approved, lgtm, size/L

#990 Fix --keep with TaskRun and PipelineRun Delete when Using --task or --pipeline Flags
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/options/delete.go
  pkg/options/delete_test.go
Labels: approved, lgtm, size/L

#1016 Fix Debian package having an incorrect package name
  tekton/debbuild/container/buildpackage.sh
Labels: approved, lgtm, size/XS

#1023 Add ClusterTriggerBinding to Useful Commands Docs
  README.md
Labels: approved, lgtm, size/XS

#1028 Fix go lint Errors from 1.27 upgrade
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: approved, lgtm, size/XS

#1027 Add Bug, Feature, and Free Form Issue Templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/free-form.md
  .github/issue-template.md
Labels: approved, lgtm, size/M

#1024 Common Way of Referring to Tekton Resources for User Facing Messages: TaskRun
  docs/cmd/tkn.md
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_cancel.md
  docs/cmd/tkn_taskrun_delete.md
  docs/cmd/tkn_taskrun_describe.md
  docs/cmd/tkn_taskrun_list.md
  docs/cmd/tkn_taskrun_logs.md
  docs/man/man1/tkn-taskrun-delete.1
  docs/man/man1/tkn-taskrun-describe.1
  docs/man/man1/tkn-taskrun-list.1
  docs/man/man1/tkn-taskrun-logs.1
  docs/man/man1/tkn-taskrun.1
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/taskrun.go
  pkg/cmd/taskrun/testdata/TestListTaskRuns-limit_taskruns_negative_case.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns-no_mixing_pipelinename_and_labels.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-limit_taskruns_negative_case.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-no_mixing_pipelinename_and_labels.golden
  pkg/deleter/deleter.go
  pkg/options/delete.go
  pkg/taskrun/description/description.go
  pkg/taskrun/get.go
Labels: approved, lgtm, size/L

#1032 Common Way of Referring to Tekton Resources for User Facing Messages: Task
  docs/cmd/tkn.md
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_delete.md
  docs/cmd/tkn_task_describe.md
  docs/cmd/tkn_task_list.md
  docs/cmd/tkn_task_logs.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-task-delete.1
  docs/man/man1/tkn-task-describe.1
  docs/man/man1/tkn-task-list.1
  docs/man/man1/tkn-task-logs.1
  docs/man/man1/tkn-task-start.1
  docs/man/man1/tkn-task.1
  pkg/cmd/task/delete.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/list.go
  pkg/cmd/task/logs.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/task.go
  test/e2e/task/task_start_test.go
Labels: approved, lgtm, size/L

#1012 Refactor v1beta1 unit tests
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/task/start_test.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#1010 Command Suggestion for Incorrect Subcommands
  docs/cmd/tkn.md
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertriggerbinding.md
  docs/cmd/tkn_condition.md
  docs/cmd/tkn_eventlistener.md
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_task.md
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_triggerbinding.md
  docs/cmd/tkn_triggertemplate.md
  pkg/cmd/root.go
  pkg/cmd/root_test.go
  pkg/suggestion/suggest.go
  pkg/suggestion/suggest_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1035 Common Way of Referring to Tekton Resources for User Facing Messages: ClusterTask
  docs/cmd/tkn.md
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_delete.md
  docs/cmd/tkn_clustertask_describe.md
  docs/cmd/tkn_clustertask_list.md
  docs/cmd/tkn_clustertask_start.md
  docs/man/man1/tkn-clustertask-delete.1
  docs/man/man1/tkn-clustertask-describe.1
  docs/man/man1/tkn-clustertask-list.1
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-clustertask.1
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/task/start_test.go
  pkg/task/tasklastrun.go
  pkg/task/tasklastrun_test.go
Labels: approved, lgtm, size/L

#1038 Common Way of Referring to Tekton Resources for User Facing Messages: Pipelines
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_delete.md
  docs/cmd/tkn_pipeline_describe.md
  docs/cmd/tkn_pipeline_list.md
  docs/cmd/tkn_pipeline_logs.md
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-delete.1
  docs/man/man1/tkn-pipeline-describe.1
  docs/man/man1/tkn-pipeline-list.1
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertriggerbinding/delete_test.go
  pkg/cmd/condition/delete_test.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/logs_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/options/delete.go
  pkg/options/delete_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/pipeline/start_test.go
Labels: approved, lgtm, size/L
