Repository tektoncd/cli, pull requests merged in 2020-08, with the labels that each got.

#1101 Add New Line for No ClusterTasks found Output
  pkg/cmd/clustertask/list.go
  test/e2e/clustertask/start_test.go
Labels: approved, lgtm, release-note, size/S

#1105 Display Results in the output of ClusterTask describe command
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/TestClusterTaskDescribe_With_Results.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_missing_param_default_one_of_everything.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_with_name_only.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_full_clustertask_multiple_taskruns.golden
Labels: approved, lgtm, release-note, size/L

#1088 Add Ability to Specify PodTemplate for TaskRun/PipelineRun
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_PodTemplate.golden
  pkg/cmd/clustertask/testdata/podtemplate.yaml
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_PodTemplate.golden
  pkg/cmd/pipeline/testdata/podtemplate.yaml
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_PodTemplate.golden
  pkg/cmd/task/testdata/podtemplate.yaml
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/pods/pod_template.go
  pkg/pods/pod_template_test.go
  pkg/pods/testdata/podtemplate-not-yaml
  pkg/pods/testdata/podtemplate-typo.yaml
  pkg/pods/testdata/podtemplate.yaml
  pkg/workspaces/workspaces.go
  pkg/workspaces/workspaces_test.go
  test/e2e/clustertask/start_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/task/start_test.go
  test/resources/podtemplate/podtemplate.yaml
Labels: approved, lgtm, release-note, size/XL

#1108 Add Triggers Installation for e2e Tests
  test/builder/builder.go
  test/builder/sort.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/clustertask/start_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/task/start_test.go
  test/resources/eventlistener.yaml
Labels: approved, lgtm, release-note-none, size/L

#1117 Fix the display of 0 Value for Timeout with tkn tr/pr describe
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_zero_timeout.golden
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_zero_timeout.golden
  pkg/pipelinerun/description/description.go
  pkg/taskrun/description/description.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1124 Add Check for Timeout Status for PipelineRun and TaskRun Cancel
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
Labels: approved, lgtm, release-note, size/L

#1126 pkg/suggestions: print help and error out 🏢
  pkg/suggestion/suggest.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#1127 pkg/suggestions: no help on subcommand errors
  pkg/suggestion/suggest.go
Labels: approved, lgtm, release-note-none, size/XS

#1098 Add EventListener Status with tkn eventlistener list
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/list_test.go
  pkg/cmd/eventlistener/testdata/TestListEventListener-Multiple_EventListener.golden
  pkg/cmd/eventlistener/testdata/TestListEventListener-Multiple_EventListener_with_output_format.golden
  test/e2e/eventListener/eventListener_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1131 Bump triggers dep to v0.7.0
  go.mod
  go.sum
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OutputYAMLWithMultipleBindingAndInterceptors.golden
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_types_convert.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1/fake/fake_trigger.go
  vendor/github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1/fake/fake_triggers_client.go
  vendor/github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1/generated_expansion.go
  vendor/github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1/trigger.go
  vendor/github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1/triggers_client.go
  vendor/github.com/tektoncd/triggers/pkg/client/informers/externalversions/generic.go
  vendor/github.com/tektoncd/triggers/pkg/client/informers/externalversions/triggers/v1alpha1/interface.go
  vendor/github.com/tektoncd/triggers/pkg/client/informers/externalversions/triggers/v1alpha1/trigger.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/client/client.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/client/fake/fake.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/factory/factory.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/factory/fake/fake.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/clustertriggerbinding/clustertriggerbinding.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/clustertriggerbinding/fake/fake.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/eventlistener/eventlistener.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/eventlistener/fake/fake.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/triggerbinding/fake/fake.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/triggerbinding/triggerbinding.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/triggertemplate/fake/fake.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/informers/triggers/v1alpha1/triggertemplate/triggertemplate.go
  vendor/github.com/tektoncd/triggers/pkg/client/listers/triggers/v1alpha1/expansion_generated.go
  vendor/github.com/tektoncd/triggers/pkg/client/listers/triggers/v1alpha1/trigger.go
  vendor/github.com/tektoncd/triggers/test/buffer.go
  vendor/github.com/tektoncd/triggers/test/builder/eventlistener.go
  vendor/github.com/tektoncd/triggers/test/e2e-tests-ingress.sh
  vendor/github.com/tektoncd/triggers/test/e2e-tests-yaml.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#1130 Consistent Error Messaging for Triggers Commands
  pkg/cmd/clustertriggerbinding/describe.go
  pkg/cmd/clustertriggerbinding/list.go
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_NonExistedName.golden
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_InvalidNamespace.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_NonExistedName.golden
  pkg/cmd/triggerbinding/describe.go
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_Invalid_Namespace.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_NonExistedName.golden
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/list.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_Invalid_Namespace.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NonExistedName.golden
Labels: approved, lgtm, release-note, size/M

#1123 Throw error when deleting tr/pr with non-existing task/pipeline
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/deleter/deleter.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1134 Copy Over PipelineRun and TaskRun Spec for --last and use run Options
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_--last.golden
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
  test/e2e/clustertask/start_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/task/start_test.go
Labels: approved, lgtm, release-note, size/L

#1141 Refactor status formatting
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
Labels: approved, lgtm, release-note, size/M

#1109 Modify --use-param-defaults flag for `pipeline start` command and add e2e test
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  test/builder/builder.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/pipeline/start_test.go
  test/resources/pipeline.yaml
Labels: approved, lgtm, release-note, size/L

#1144 Refactor taskrun description
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_With_Workspaces.golden
  pkg/taskrun/description/description.go
Labels: approved, lgtm, release-note, size/S

#1147 Update README for v0.12.0
  README.md
Labels: approved, lgtm, release-note-none, size/M
