Repository tektoncd/cli, pull requests merged in 2020-05, with the labels that each got.

#954 Remove tkn create -f
  docs/cmd/tkn_resource_create.md
  docs/man/man1/tkn-resource-create.1
  pkg/cmd/pipeline/create.go
  pkg/cmd/pipeline/create_test.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/testdata/pipelinerun.yaml
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/testdata/pipelineresource.yaml
  pkg/cmd/pipelineresource/testdata/pipelinerun.yaml
  pkg/cmd/task/create.go
  pkg/cmd/task/create_test.go
  pkg/cmd/task/task.go
  pkg/cmd/task/testdata/taskrun.yaml
Labels: approved, lgtm, size/XL

#953 Bump plumbing to recent master 👼
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#935 Add Task start E2E tests
  test/e2e/build_templates.go
  test/e2e/cli.go
  test/e2e/helper.go
  test/e2e/init_test.go
  test/e2e/pipeline_e2e_test.go
  test/e2e/task_start_e2e_test.go
  test/environment/environment.go
  test/resources/read-file.yaml
Labels: approved, lgtm, size/L

#967 Update Readme with s390x build usage
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#973 Fix triggerbinding and template `list` error messages
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggertemplate/list.go
Labels: approved, lgtm, size/S

#975 Enable yaml lint
  tekton/get-version.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#974 Refactoring for --all-namespace flag
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/task/list.go
  pkg/cmd/taskrun/list.go
  pkg/cmd/taskrun/list_test.go
Labels: approved, lgtm, size/M

#961 Makefile changes for new skipCheckFlag
  Makefile
Labels: approved, lgtm, size/S

#978 Fix to provide an error for tkn completion without argument
  pkg/cmd/completion/completion.go
  pkg/cmd/completion/completion_test.go
Labels: approved, lgtm, ok-to-test, size/M

#947 Improve get pipelines version func
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm, size/L

#981 Add triggers version info to the version command
  pkg/cmd/version/testdata/TestVersionGood.golden
  pkg/cmd/version/version.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm, size/L

#985 Switch to sigs.k8s.io/yaml for Yaml Unmarshal
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/pipeline-invalid-v1alpha1.yaml
  pkg/cmd/pipeline/testdata/pipeline-invalid-v1beta1.yaml
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/task-invalid-v1alpha1.yaml
  pkg/cmd/task/testdata/task-invalid-v1beta1.yaml
Labels: approved, lgtm, size/L

#986 Fix 'Edit this page' and 'Create an issue' links on the website
  docs/README.md
Labels: approved, lgtm, size/XS

#979 Restructure e2e Tests to Improve Organization
  test/e2e-tests.sh
  test/e2e/pipeline/pipeline_test.go
  test/e2e/task/task_start_test.go
Labels: approved, lgtm, size/L

#971 Add no-headers and all-namespaces flags for `resource list`
  docs/cmd/tkn_resource_list.md
  docs/man/man1/tkn-resource-list.1
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-All_Namespaces.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-No_Headers.golden
  pkg/pipelineresource/sort/by_namespace.go
  pkg/pipelineresource/sort/by_namespace_test.go
  pkg/pipelineresource/sort/by_type_and_name.go
  pkg/pipelineresource/sort/by_type_and_name_test.go
Labels: approved, lgtm, size/L

#960 Provides `--last` option of the `describe` of PipelineRun/TaskRun to describe the most recent PipelineRun/TaskRun
  docs/cmd/tkn_pipelinerun_describe.md
  docs/cmd/tkn_taskrun_describe.md
  docs/man/man1/tkn-pipelinerun-describe.1
  docs/man/man1/tkn-taskrun-describe.1
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_last.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_lastV1beta1.golden
  pkg/cmd/taskrun/describe.go
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_last.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_lastV1beta1.golden
  pkg/options/describe.go
Labels: approved, lgtm, ok-to-test, size/XL

#996 Change Taskrun and PipelineRun Delete Test Names
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/task/delete_test.go
Labels: approved, lgtm, size/XS

#993 Fix tkn task delete <name> --trs deletes ClusterTaskrun also
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
Labels: approved, lgtm, ok-to-test, size/M

#991 Display conditions in the pipeline describe command
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_task_conditions.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_multiple_v1alpha1_pipelineruns.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_run.golden
  pkg/formatted/conditions.go
  pkg/formatted/conditions_test.go
  test/e2e/build_templates.go
Labels: approved, lgtm, size/L

#987 Task start interactive mode
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_-f_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json_-f_v1beta1.golden
  pkg/options/start.go
Labels: approved, lgtm, size/XL

#989 Fix to provide error in case of no pr logs
  pkg/cmd/pipelinerun/logs_test.go
  pkg/log/pipeline_reader.go
Labels: approved, lgtm, ok-to-test, size/S
