Repository tektoncd/cli, pull requests merged in 2020-09, with the labels that each got.

#1148 Use latest release.yaml
  test/e2e-common.sh
Labels: approved, lgtm, release-note-none, size/XS

#1138 Show the version of dashboard
  pkg/cmd/version/testdata/TestVersionGood.golden
  pkg/cmd/version/version.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1152 Disable colouring when the user set the variable NO_COLOR
  pkg/flags/flags.go
Labels: approved, lgtm, release-note, size/XS

#1089 Adds support for EventListener URL with List and Describe command
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/describe_test.go
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/list_test.go
  pkg/cmd/eventlistener/testdata/TestListEventListener-Multiple_EventListener.golden
  pkg/formatted/address.go
  pkg/formatted/address_test.go
Labels: approved, lgtm, release-note, size/L

#1161 Fix golangci-lint 1.31 gocritic Issues
  cmd/docs/man_docs.go
  cmd/docs/md_docs.go
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/task/start_test.go
  pkg/cmd/taskrun/logs_test.go
  pkg/formatted/color.go
  pkg/pipeline/pipelinelastrun.go
  pkg/pipelinerun/tracker.go
  pkg/pods/pod.go
  pkg/task/tasklastrun.go
  pkg/test/dynamic/clientset/clientset.go
  test/builder/builder.go
  test/e2e/resource/create_test.go
  test/framework/helper.go
  test/wait/helper-wait.go
  test/wait/wait.go
Labels: approved, lgtm, release-note-none, size/L

#1159 Do not Sort TaskRuns or PipelineRuns if keep=0
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/taskrun/delete.go
Labels: approved, lgtm, release-note-none, size/S

#1158 Fix slowness in executing tkn commands
  pkg/actions/gvr.go
  pkg/cmd/clustertask/testdata/TestClusterTaskListOnlyClusterTasks.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_with_no_arguments.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Failure_from_listing_taskruns.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_output=json.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_timeout_v1beta1.golden
  pkg/cmd/clustertriggerbinding/clustertriggerbinidng_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_using_--filename.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_pipelineruns_in_all_namespaces_without_headers.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_pipelineruns_without_headers.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json_-f.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-print_taskrunsruns_in_all_namespaces.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_custom_timeout.golden
  pkg/pipelinerun/tracker_test.go
  pkg/test/builder/apiresource.go
  pkg/test/params.go
Labels: approved, lgtm, release-note, size/XL

#1167 Update Condition Tests from Test Builders to Structs
  pkg/cmd/condition/delete_test.go
  pkg/cmd/condition/describe_test.go
  pkg/cmd/condition/list_test.go
Labels: approved, lgtm, release-note-none, size/L

#1173 Update README Versions for v0.12.1
  README.md
Labels: approved, lgtm, release-note-none, size/M

#1176 Artwork/Logo added to the top of the README.
  README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#1172 Fix rpm build for release
  tekton/rpmbuild/README.md
  tekton/rpmbuild/build.sh
  tekton/rpmbuild/rpmbuild-run.yml
  tekton/rpmbuild/rpmbuild.yml
Labels: approved, lgtm, release-note-none, size/M

#1168 Update ClusterTask Tests from Test Builders to Structs
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_no_output_v1beta1.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_Run_with_--use-param-defaults_and_specified_params.golden
Labels: approved, lgtm, release-note-none, size/XL

#1179 Use --prefix-name option for tkn clustertask start
  docs/cmd/tkn_clustertask_start.md
  docs/man/man1/tkn-clustertask-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_Run_with_--prefix-name.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_Run_with_--prefix-name_and_--last.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_Run_with_--prefix-name_and_--last_v1beta1.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_Run_with_--prefix-name_v1beta1.golden
Labels: approved, lgtm, release-note, size/L

#1182 Update PipelineResource Tests from Test Builders to Structs
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelineresource/list_test.go
Labels: approved, lgtm, release-note-none, size/L

#1183 Remove release-note block indentation in PR template 🌮
  .github/pull_request_template.md
Labels: approved, lgtm, release-note-none, size/S

#1092 Modify tkn version to accept namespace as ldflag and flag
  Makefile
  docs/cmd/tkn_version.md
  docs/man/man1/tkn-version.1
  pkg/cmd/version/testdata/TestVersionGood.golden
  pkg/cmd/version/version.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm, release-note, size/L

#1186 Fix deployment fetch issue for multiple namespaces
  pkg/version/version.go
Labels: approved, lgtm, release-note-none, size/XS

#1185 Cancelling a pipelinerun which failed with `Failed(Cancelled)` throws an error
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
Labels: approved, lgtm, release-note, size/M

#1187 Enable auto-select support in pipelineDescribe if only one pipeline is present
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_WithoutNameIfOnlyOnePipelinePresent.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_WithoutNameOfOnlyOnePipelinePresent.golden
Labels: approved, lgtm, release-note, size/L

#1156 Add --use-taskrun for ClusterTask start
  docs/cmd/tkn_clustertask_start.md
  docs/man/man1/tkn-clustertask-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_--last.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start_v1beta1-Dry_run_with_--last.golden
  pkg/cmd/task/start.go
  pkg/options/start.go
  test/e2e/clustertask/start_test.go
Labels: approved, lgtm, release-note, size/L

#1190 Enable auto select support in PipelineRunDescribe if only one PipelineRun Present
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribeV1beta1_withoutNameOfOnlyOnePipelineRunPresent.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_withoutNameOfOnlyOnePipelineRunPresent.golden
Labels: approved, lgtm, release-note, size/L

#1194 Update README to v0.13.0
  README.md
Labels: approved, lgtm, release-note-none, size/M
