Repository tektoncd/cli, pull requests merged in 2020-12, with the labels that each got.

#1178 Basic execution plugin module
  cmd/tkn/main.go
  go.mod
  test/e2e/plugin/plugin_test.go
  test/e2e/plugin/tkn-failure
  test/e2e/plugin/tkn-success
  vendor/gotest.tools/v3/env/env.go
  vendor/gotest.tools/v3/internal/cleanup/cleanup.go
  vendor/gotest.tools/v3/x/subtest/context.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1242 Allow --prefix-name and --timeout to be Overrode when using --last or --use-run Options
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
Labels: approved, lgtm, release-note, size/L

#1250 Ignore --follow flag when TaskRun or PipelineRun is done
  pkg/cmd/taskrun/logs_test.go
  pkg/log/pipeline_reader.go
  pkg/log/task_reader.go
Labels: approved, lgtm, ok-to-test, release-note, size/S

#1267 Bumps Hub CLI Dependency
  docs/cmd/tkn_hub.md
  docs/cmd/tkn_hub_downgrade.md
  docs/cmd/tkn_hub_downgrade_task.md
  docs/cmd/tkn_hub_get_task.md
  docs/cmd/tkn_hub_info.md
  docs/cmd/tkn_hub_info_task.md
  docs/cmd/tkn_hub_install.md
  docs/cmd/tkn_hub_install_task.md
  docs/cmd/tkn_hub_reinstall.md
  docs/cmd/tkn_hub_reinstall_task.md
  docs/cmd/tkn_hub_upgrade.md
  docs/cmd/tkn_hub_upgrade_task.md
  docs/man/man1/tkn-hub-downgrade-task.1
  docs/man/man1/tkn-hub-downgrade.1
  docs/man/man1/tkn-hub-get-task.1
  docs/man/man1/tkn-hub-info-task.1
  docs/man/man1/tkn-hub-info.1
  docs/man/man1/tkn-hub-install-task.1
  docs/man/man1/tkn-hub-install.1
  docs/man/man1/tkn-hub-reinstall-task.1
  docs/man/man1/tkn-hub-reinstall.1
  docs/man/man1/tkn-hub-upgrade-task.1
  docs/man/man1/tkn-hub-upgrade.1
  docs/man/man1/tkn-hub.1
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-version/.travis.yml
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/downgrade/downgrade.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/get/get.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/get/task.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/info/info.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/install/install.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/reinstall/reinstall.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/root.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/search/search.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/upgrade/upgrade.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/formatter/field.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource_version.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/hub.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/installer/action.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/installer/config.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/installer/gvr.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/installer/kube_action.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/kube/client.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/printer/print.go
  vendor/github.com/tektoncd/hub/api/pkg/parser/parser.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#1265 Hoist an ActivityTimeout option.
  pkg/log/pipeline_reader.go
  pkg/log/reader.go
  pkg/log/task_reader.go
  pkg/options/logs.go
Labels: approved, lgtm, release-note-none, size/M

#1269 Remove --check Shorthand and Add Global Flags to Version Command
  docs/cmd/tkn_version.md
  docs/man/man1/tkn-version.1
  pkg/cmd/version/version.go
Labels: approved, lgtm, release-note, size/M

#1274 Update README to 0.15.0
  README.md
Labels: approved, lgtm, release-note-none, size/M

#1271 Use python3 binary instead of python or we won't find it
  tekton/rpmbuild/build.sh
Labels: approved, lgtm, release-note, size/XS

#1272 Debian package: Do not use tkn version as a check
  tekton/debbuild/control/rules
Labels: approved, lgtm, release-note, size/XS

#1276 Refactor e2e scripts and fix tests
  test/e2e-tests.sh
  test/e2e/pipeline/pipeline_test.go
  test/resources/podtemplate/podtemplate.yaml
Labels: approved, lgtm, release-note-none, size/M
