Repository tektoncd/cli, pull requests merged in 2020-11, with the labels that each got.

#1232 Deprecate -c Shorthand for tkn version --check
  docs/cmd/tkn_version.md
  docs/man/man1/tkn-version.1
  pkg/cmd/version/version.go
Labels: approved, lgtm, release-note, size/XS

#1225 Bump pipeline and triggers deps
  go.mod
  go.sum
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/describe_test.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithTriggerBindingName.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OutputYAMLWithMultipleBindingAndInterceptors.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_TriggerWithTriggerTemplateRef.golden
  third_party/VENDOR-LICENSE/LICENSE
  third_party/VENDOR-LICENSE/github.com/dimfeld/httptreemux/v5/LICENSE
  third_party/VENDOR-LICENSE/github.com/gorilla/websocket/LICENSE
  third_party/VENDOR-LICENSE/github.com/mitchellh/go-homedir/LICENSE
  third_party/VENDOR-LICENSE/github.com/tektoncd/hub/api/LICENSE
  third_party/VENDOR-LICENSE/goa.design/goa/v3/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/crypto/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/net/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/text/LICENSE
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/triggers/test/builder/trigger.go
  vendor/github.com/tektoncd/triggers/test/e2e-tests-ingress.sh
  vendor/github.com/tektoncd/triggers/test/raw.go
  vendor/knative.dev/pkg/ptr/doc.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL

#1227 Do Not Delete ClusterTask TaskRuns with --task Flag
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/taskrun/list.go
  pkg/task/tasklastrun.go
Labels: approved, lgtm, release-note, size/L

#1237 Fix APIversion not shown on describe commands
  pkg/cmd/clustertriggerbinding/describe.go
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_WithOutputName.golden
  pkg/cmd/clustertriggerbinding/testdata/TestClusterTriggerBindingDescribe_WithOutputYaml.golden
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OutputYAMLWithMultipleBindingAndInterceptors.golden
  pkg/cmd/triggerbinding/describe.go
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithOutputName.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithOutputYaml.golden
  pkg/cmd/triggertemplate/describe.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOutputName.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOutputYaml.golden
Labels: approved, lgtm, release-note, size/S

#1234 Add --all-namespaces flag to tkn triggerbinding list command
  docs/cmd/tkn_triggerbinding_list.md
  docs/man/man1/tkn-triggerbinding-list.1
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggerbinding/list_test.go
  pkg/cmd/triggerbinding/testdata/TestListTriggerBinding-TriggerBindings_from_all_namespaces.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1236 Add --all-namespaces flag to tkn eventlistener list command
  docs/cmd/tkn_eventlistener_list.md
  docs/man/man1/tkn-eventlistener-list.1
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/list_test.go
  pkg/cmd/eventlistener/testdata/TestListEventListener-EventListeners_from_all-namespaces.golden
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1235 Add --all-namespaces flag to TriggerTemplate List subcommand
  docs/cmd/tkn_triggertemplate_list.md
  docs/man/man1/tkn-triggertemplate-list.1
  pkg/cmd/triggertemplate/list.go
  pkg/cmd/triggertemplate/list_test.go
  pkg/cmd/triggertemplate/testdata/TestListTriggerTemplate-TriggerTemplates_from_all_namespaces.golden
Labels: approved, lgtm, release-note, size/M

#1238 Make sure we target LTS for ubuntus
  README.md
  tekton/debbuild/container/Dockerfile
Labels: approved, lgtm, release-note, size/S

#1241 Add --all-namespaces flag to tkn condition list command
  docs/cmd/tkn_condition_list.md
  docs/man/man1/tkn-condition-list.1
  pkg/cmd/condition/list.go
  pkg/cmd/condition/list_test.go
  pkg/cmd/condition/testdata/TestConditionList-Conditions_from_all_namespaces.golden
  pkg/cmd/condition/testdata/TestConditionList-No_conditions_found_in_all_namespaces.golden
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1249 Remove EventListener Log Output Assertion from e2e Tests
  test/e2e/eventListener/eventListener_test.go
Labels: approved, lgtm, release-note-none, size/S

#1251 bump pipleine dependency to v0.18.0
  go.mod
  go.sum
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/doc.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/template.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/substitution.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/remote/oci/resolver.go
  vendor/github.com/tektoncd/pipeline/pkg/remote/resolver.go
  vendor/github.com/tektoncd/pipeline/test/README.md
  vendor/github.com/tektoncd/pipeline/test/build_logs.go
  vendor/github.com/tektoncd/pipeline/test/e2e-common.sh
  vendor/github.com/tektoncd/pipeline/test/multiarch_utils.go
  vendor/github.com/tektoncd/pipeline/test/remote.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/build_logs.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/wait.go
  vendor/github.com/tektoncd/pipeline/test/wait.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#1245 fix function name typo
  pkg/cmd/clustertask/start.go
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#1252 Makefile: remove darwin/386 from cross target 🌮
  Makefile
Labels: approved, lgtm, release-note, size/XS

#1244 Add --no-headers flag to tkn clustertask list command
  docs/cmd/tkn_clustertask_list.md
  docs/man/man1/tkn-clustertask-list.1
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/list_test.go
  pkg/cmd/clustertask/testdata/TestClusterTaskListNoHeadersv1alpha1.golden
  pkg/cmd/clustertask/testdata/TestClusterTaskListNoHeadersv1beta1.golden
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1243 Add --no-headers flag to tkn clustertriggerbinding list command
  docs/cmd/tkn_clustertriggerbinding_list.md
  docs/man/man1/tkn-clustertriggerbinding-list.1
  pkg/cmd/clustertriggerbinding/list.go
  pkg/cmd/clustertriggerbinding/list_test.go
  pkg/cmd/clustertriggerbinding/testdata/TestListClusterTriggerBinding-List_ClusterTriggerBindings_without_headers.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1260 Use goreleaser task from tektoncd/catalog
  tekton/goreleaser.yml
  tekton/release.sh
Labels: approved, lgtm, release-note, size/M

#1261 update README to v0.14.0
  README.md
Labels: approved, lgtm, release-note, size/M

#1259 Add --no-headers flag to tkn condition list command
  docs/cmd/tkn_condition_list.md
  docs/man/man1/tkn-condition-list.1
  pkg/cmd/condition/list.go
  pkg/cmd/condition/list_test.go
  pkg/cmd/condition/testdata/TestConditionList-List_conditions_from_all_namespaces_without_headers.golden
  pkg/cmd/condition/testdata/TestConditionList-List_conditions_without_headers.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1257 📦 Use VERSION file debian/versiion for debian package if we find it
  tekton/debbuild/container/buildpackage.sh
  tekton/debbuild/control/rules
Labels: approved, lgtm, release-note-none, size/XS

#1254 Add --no-headers flag to tkn triggerbinding list command
  docs/cmd/tkn_triggerbinding_list.md
  docs/man/man1/tkn-triggerbinding-list.1
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggerbinding/list_test.go
  pkg/cmd/triggerbinding/testdata/TestListTriggerBinding-List_TriggerBindings_from_all_namespaces_without_headers.golden
  pkg/cmd/triggerbinding/testdata/TestListTriggerBinding-List_TriggerBindings_without_headers.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1255 Add --no-headers flag to tkn triggertemplate list command
  docs/cmd/tkn_triggertemplate_list.md
  docs/man/man1/tkn-triggertemplate-list.1
  pkg/cmd/triggertemplate/list.go
  pkg/cmd/triggertemplate/list_test.go
  pkg/cmd/triggertemplate/testdata/TestListTriggerTemplate-List_TriggerTemplates_from_all_namespaces_without_headers.golden
  pkg/cmd/triggertemplate/testdata/TestListTriggerTemplate-List_TriggerTemplates_without_headers.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1258 Add --no-headers flag to tkn eventlistener list command
  docs/cmd/tkn_eventlistener_list.md
  docs/man/man1/tkn-eventlistener-list.1
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/list_test.go
  pkg/cmd/eventlistener/testdata/TestListEventListener-List_EventListeners_from_all_namespaces_without_headers.golden
  pkg/cmd/eventlistener/testdata/TestListEventListener-List_EventListeners_without_headers.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M
