Repository tektoncd/cli, pull requests merged in 2021-07, with the labels that each got.

#1410 Fix CLI installation instructions for deb-based distros
  docs/README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#1393 Get tekton components version from configmap
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm, release-note, size/L

#1415 Force cancel when using tkn pipelinerun cancel 👼
  internal/builder/v1beta1/pipeline.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelinerun/cancel.go
  pkg/pipelinerun/pipelinerun.go
Labels: approved, lgtm, release-note, size/S

#1408 Fix client version output with --component option
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-triggers.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-triggers.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-triggers.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-triggers.golden
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1385 Fix TaskRun order in `tkn pr logs`
  pkg/cmd/pipelinerun/logs_test.go
  pkg/taskrun/taskrun.go
Labels: approved, lgtm, release-note, size/M

#1419 Get default sa from configmap defaultconfigs
  test/e2e-tests.sh
  test/framework/helper.go
Labels: approved, lgtm, release-note, size/S

#1420 Update tkn version to 0.20.0
  README.md
Labels: approved, lgtm, release-note, size/M

#1428 Fix e2e test failing
  test/e2e/clustertask/start_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/pipeline/start_test.go
  test/resources/git-resource.yaml
  test/resources/output-pipelinerun.yaml
Labels: approved, lgtm, release-note, size/S

#1427 Remove golden files generated while testing version command
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_only_with_pipeline_installed-triggers.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline,_triggers_and_dashboard_installed-triggers.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_dashboard_installed-triggers.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-client.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-dashboard.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-pipeline.golden
  pkg/cmd/version/testdata/TestGetComponentVersions/deployment_with_pipeline_and_triggers_installed-triggers.golden
  pkg/cmd/version/version_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/M

#1424 fix rpm build
  tekton/rpmbuild/tekton.spec
Labels: approved, lgtm, release-note, size/XS
