Repository tektoncd/cli, pull requests merged in 2021-03, with the labels that each got.

#1315 Fix eventListener e2e test with new RBAC permissions
  test/e2e/eventListener/eventListener_test.go
  test/resources/eventlistener/eventlistener.yaml
Labels: approved, lgtm, release-note-none, size/M

#1318 Fix Typos 🧑‍💻
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/options/start.go
Labels: approved, lgtm, release-note, size/S

#1321 master -> main in release.sh
  tekton/release.sh
Labels: approved, lgtm, release-note, size/S

#1322 fix release script
  tekton/release.sh
Labels: approved, lgtm, release-note, size/XS

#1323 correct path in release.sh
  tekton/release.sh
Labels: approved, lgtm, release-note, size/XS

#1324 increase golint timeout
  tekton/release-pipeline.yml
Labels: approved, lgtm, release-note, size/XS

#1309 Fix parseParam with empty array
  pkg/params/mergeparams.go
  pkg/params/mergeparams_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1325 tkn verion v0.16.0 to v0.17.0
  README.md
Labels: approved, lgtm, release-note, size/M

#1332 Fix clustertask start command with --last flag
  pkg/cmd/clustertask/start_test.go
  pkg/task/tasklastrun.go
  pkg/task/tasklastrun_test.go
Labels: approved, lgtm, size/L

#1338 Print status in `tkn p start` if it is not nil
  pkg/cmd/pipeline/start.go
Labels: approved, lgtm, release-note-none, size/XS

#1341 Fix clustertask describe and delete, task lastrun
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/task/tasklastrun.go
  pkg/task/tasklastrun_test.go
Labels: approved, lgtm, release-note, size/M
