Repository tektoncd/cli, pull requests merged in 2021-04, with the labels that each got.

#1342 Update readme for v0.17.1
  README.md
Labels: approved, lgtm, release-note, size/M

#1344 Fixes the bundle push and list commands to conform to the bundle spec.
  docs/cmd/tkn_bundle.md
  docs/cmd/tkn_bundle_list.md
  docs/cmd/tkn_bundle_push.md
  docs/man/man1/tkn-bundle-list.1
  docs/man/man1/tkn-bundle-push.1
  pkg/bundle/builder.go
  pkg/bundle/builder_test.go
  pkg/bundle/reader.go
  pkg/bundle/reader_test.go
  pkg/cmd/bundle/list.go
  pkg/cmd/bundle/list_test.go
  pkg/cmd/bundle/push.go
  pkg/cmd/bundle/push_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/L

#1317 Adds version in describe command of task
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  pkg/cmd/task/testdata/TestTaskDescribe_With_Different_Labels.golden
  pkg/cmd/task/testdata/TestTaskDescribe_With_Empty_Labels.golden
  pkg/cmd/task/testdata/TestTaskV1beta1Describe_Full.golden
  pkg/formatted/version.go
  pkg/formatted/version_test.go
Labels: approved, lgtm, release-note, size/L

#1349 Update README with the version of supported RPMs distros
  README.md
Labels: approved, lgtm, release-note, size/XS

#1351 Update readme for tkn 0.17.2
  README.md
Labels: approved, lgtm, release-note-none, size/M

#1330 feature/update PowerShell completion
  README.md
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONDUCT.md
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, release-note, size/XL

#1310 Add framework usage to get kubeconfig and cluster params support
  test/e2e/plugin/plugin_test.go
Labels: approved, lgtm, release-note-none, size/XS

#1358 Update plumbing dep to pin gke version
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/M

#1357 Fix README to point to v0.17.2 release
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#1333 Add support for tkn clustertask logs
  docs/cmd/tkn_clustertask.md
  docs/cmd/tkn_clustertask_logs.md
  docs/man/man1/tkn-clustertask-logs.1
  docs/man/man1/tkn-clustertask.1
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertask/logs.go
  pkg/cmd/clustertask/logs_test.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/taskrun/logs_test.go
  pkg/log/task_reader.go
  pkg/options/logs.go
  pkg/options/logs_test.go
Labels: approved, lgtm, release-note, size/XL

#1353 Auto-select EventListener in describe if only one is present
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/describe_test.go
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_AutoSelect.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_NoArgProvided.golden
  pkg/eventlistener/eventlistener.go
  pkg/eventlistener/eventlistener_test.go
  pkg/options/describe.go
  pkg/options/describe_test.go
  pkg/options/resource_names.go
Labels: approved, lgtm, release-note, size/L

#1361 update cli version to v0.18.0 in readme
  README.md
Labels: approved, lgtm, release-note, size/M
