Repository tektoncd/cli, pull requests merged in 2021-02, with the labels that each got.

#1289 Update Task Tests from Test Builders to Structs
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/task/start_test.go
Labels: approved, lgtm, release-note-none, size/XXL

#1300 Update trigger dep to v0.11.2
  go.mod
  go.sum
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/describe_test.go
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_MultipleTriggers.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithMultipleTriggerBinding.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_OneTriggerWithTriggerBindingName.golden
  pkg/cmd/eventlistener/testdata/TestEventListenerDescribe_WithMultipleBindingAndInterceptors.golden
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/interceptor_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/triggers/pkg/client/injection/client/client.go
  vendor/github.com/tektoncd/triggers/test/builder/eventlistener.go
  vendor/github.com/tektoncd/triggers/test/builder/trigger.go
  vendor/github.com/tektoncd/triggers/test/controller.go
  vendor/github.com/tektoncd/triggers/test/raw.go
  vendor/github.com/tektoncd/triggers/test/resources.go
  vendor/github.com/tektoncd/triggers/test/signature.go
  vendor/knative.dev/pkg/ptr/doc.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1301 Update readme for tkn 0.16.0
  README.md
Labels: approved, lgtm, release-note-none, size/M

#1306 Use tkn create pipeline in release.sh
  tekton/release.sh
  tekton/volume-claim-template.yml
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1303 Fix crash with pipeline describe when using inline taskSpec
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_taskSpec.golden
  pkg/formatted/task.go
Labels: approved, lgtm, release-note, size/L

#1305 nix/nixos install notes
  README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS
