Repository tektoncd/cli, pull requests merged in 2021-08, with the labels that each got.

#1429 Update README.md
  README.md
Labels: size/XS, lgtm, approved, ok-to-test, release-note

#1326 Support `output` option for pipeline/task `start` command
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: lgtm, approved, size/M, ok-to-test, release-note

#1430 Authenticate to registries with Podman's config
  docs/cmd/tkn_bundle_list.md
  docs/cmd/tkn_bundle_push.md
  docs/man/man1/tkn-bundle-list.1
  docs/man/man1/tkn-bundle-push.1
  go.mod
  go.sum
  pkg/bundle/flags.go
  pkg/bundle/keychain.go
  pkg/bundle/keychain_test.go
  pkg/cmd/bundle/list.go
  pkg/cmd/bundle/push.go
Labels: lgtm, approved, size/L, ok-to-test, release-note

#1434 Fix link in doc
  DEVELOPMENT.md
Labels: size/XS, lgtm, approved, release-note

#1378 Add choco package to tkn repo
  choco/README.md
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: lgtm, approved, size/M, release-note-none
