Repository tektoncd/cli, pull requests merged in 2021-06, with the labels that each got.

#1093 Added --component option to just output the version of the components like client|pipeline|triggers
  docs/cmd/tkn_version.md
  docs/man/man1/tkn-version.1
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1069 Gives a validation error if any `param` does not have a type defined in the task/pipeline definition
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/pipeline-v1beta1-parameter-with-invalid-type.yaml
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/task-v1beta1-param-with-invalid-type.yaml
  pkg/params/validation.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#1379 Fixes pipeline start to ask for params interactively if not passed
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json_-f_v1alpha1.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_PodTemplate.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_output=json_-f_v1beta1.golden
  test/e2e/pipeline/start_test.go
Labels: approved, lgtm, release-note, size/L

#1376 Fixes clusterTask start to ask for params interactively if not passed
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/options/start.go
  test/e2e/clustertask/start_test.go
Labels: approved, lgtm, release-note, size/M

#1377 Add support for optional workspaces in tkn start
  pkg/cmd/pipeline/start.go
  pkg/options/start.go
  test/e2e/clustertask/start_test.go
  test/e2e/pipeline/start_test.go
  test/e2e/task/start_test.go
  test/resources/clustertask-with-optional-workspace.yaml
  test/resources/pipeline-with-optional-workspace.yaml
  test/resources/task-with-optional-workspace.yaml
Labels: approved, lgtm, release-note, size/L

#1380 Fix rpm spec file
  tekton/rpmbuild/tekton.spec
Labels: approved, lgtm, release-note-none, size/XS

#1354 Common Description for workspace flag in start command
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  docs/reference/cmd/pipeline_start.md
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: approved, lgtm, release-note-none, size/L

#1304 Add a flag to not print the taskname/step prefix when showing logs
  docs/cmd/tkn_pipelinerun_logs.md
  docs/cmd/tkn_taskrun_logs.md
  docs/man/man1/tkn-pipelinerun-logs.1
  docs/man/man1/tkn-taskrun-logs.1
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/taskrun/logs.go
  pkg/cmd/taskrun/logs_test.go
  pkg/log/writer.go
  pkg/options/logs.go
Labels: approved, lgtm, release-note, size/L

#1384 Replace maze.io/x/duration with its redirect
  go.mod
  go.sum
Labels: approved, lgtm, release-note-none, size/XS

#1391 Update readme for latest version
  README.md
Labels: approved, lgtm, release-note-none, size/M

#1390 Fix version command outputting empty
  pkg/cmd/version/version.go
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#1392 Add --keep-since flag to pipelinerun delete
  docs/cmd/tkn_pipelinerun_delete.md
  docs/man/man1/tkn-pipelinerun-delete.1
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/options/delete.go
Labels: approved, lgtm, release-note, size/L

#1396 Fix broken links in DEVELOPMENT.MD
  DEVELOPMENT.md
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1400 Fix typo with my name
  docs/README.md
Labels: approved, lgtm, release-note, size/XS

#1401 Add link to tkn bundle to main readme 🔗
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#1403 Update README about coloring being disabled
  README.md
Labels: approved, lgtm, release-note, size/S

#1405 fix default --prefix=false with p/t/ct start
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
Labels: approved, lgtm, release-note, size/XS

#1402 Add pipelinerun delete by label
  docs/cmd/tkn_pipelinerun_delete.md
  docs/man/man1/tkn-pipelinerun-delete.1
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/options/delete.go
Labels: approved, lgtm, release-note, size/S

#1409 update readme cli version to v0.19.1
  README.md
Labels: approved, lgtm, release-note, size/M
