Repository tektoncd/cli, pull requests merged in 2021-09, with the labels that each got.

#1447 Bump hub dependency with latest updates
  docs/cmd/tkn_hub.md
  docs/cmd/tkn_hub_search.md
  docs/man/man1/tkn-hub-search.1
  go.mod
  go.sum
  vendor/github.com/tektoncd/hub/api/gen/http/resource/client/cli.go
  vendor/github.com/tektoncd/hub/api/gen/http/resource/client/encode_decode.go
  vendor/github.com/tektoncd/hub/api/gen/http/resource/client/types.go
  vendor/github.com/tektoncd/hub/api/gen/resource/service.go
  vendor/github.com/tektoncd/hub/api/gen/resource/views/view.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/info/info.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/install/install.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/search/search.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/formatter/field.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/search.go
  vendor/github.com/tektoncd/hub/api/pkg/parser/catalog.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL, release-note

#1449 Update triggerbinding cmd to v1beta1
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggerbinding/describe.go
  pkg/cmd/triggerbinding/describe_test.go
  pkg/cmd/triggerbinding/list.go
  pkg/cmd/triggerbinding/list_test.go
  pkg/cmd/triggerbinding/main_test.go
  pkg/cmd/triggerbinding/testdata/TestListTriggerBinding-List_TriggerBindings_without_headers.golden
  pkg/cmd/triggerbinding/testdata/TestTriggerBindingDescribe_WithOutputYaml.golden
  pkg/cmd/triggerbinding/triggerbinding.go
  pkg/test/builder/unstructured.go
  pkg/test/dynamic/clientset/tekton.go
  pkg/test/dynamic/dynamictestclient.go
  pkg/triggerbinding/main_test.go
  pkg/triggerbinding/triggerbinding.go
  pkg/triggerbinding/triggerbinding_test.go
Labels: lgtm, approved, size/L, release-note

#1453 Cleanup missed during v1beta1 work
  pkg/triggerbinding/triggerbinding_test.go
Labels: lgtm, approved, size/S, release-note-none

#1445 Adds ignore-running flag to pr,tr delete cmd
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_taskrun_delete.md
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-taskrun-delete.1
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/options/delete.go
Labels: lgtm, approved, size/L, release-note

#1454 Update eventlistener list and delete cmd
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/eventlistener/describe.go
  pkg/cmd/eventlistener/eventlistener.go
  pkg/cmd/eventlistener/list.go
  pkg/cmd/eventlistener/list_test.go
  pkg/cmd/eventlistener/testdata/TestListEventListener-List_EventListeners_without_headers.golden
  pkg/eventlistener/eventlistener.go
  pkg/eventlistener/eventlistener_test.go
  pkg/eventlistener/main_test.go
  pkg/test/builder/unstructured.go
  pkg/test/dynamic/clientset/tekton.go
  pkg/test/dynamic/dynamictestclient.go
Labels: lgtm, approved, size/L, release-note
