Repository tektoncd/cli, pull requests merged in 2022-03, with the labels that each got.

#1509 Adds chains version in output of tkn version command
  docs/cmd/tkn_version.md
  docs/man/man1/tkn-version.1
  pkg/cmd/version/testdata/TestGetVersions-deployment_with_pipeline,_chains,_triggers,_dashboard_and_operator_installed.golden
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: lgtm, approved, size/M, ok-to-test, release-note

#1518 remove unnecessary filepath join
  pkg/bundle/keychain_test.go
Labels: size/XS, lgtm, approved, ok-to-test, release-note

#1519 Bump Tekton Hub CLI to latest
  docs/cmd/tkn_hub_reinstall_task.md
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/github.com/hako/durafmt/README.md
  vendor/github.com/hako/durafmt/durafmt.go
  vendor/github.com/hako/durafmt/go.mod
  vendor/github.com/hako/durafmt/unit.go
  vendor/github.com/tektoncd/hub/LICENSE
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/downgrade/downgrade.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/get/get.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/get/task.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/install/install.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/reinstall/reinstall.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/cmd/upgrade/upgrade.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource_version.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/hub.go
  vendor/github.com/tektoncd/hub/api/pkg/git/fetch_spec.go
  vendor/github.com/tektoncd/hub/api/pkg/git/git.go
  vendor/github.com/tektoncd/hub/api/v1/gen/http/resource/client/cli.go
  vendor/github.com/tektoncd/hub/api/v1/gen/http/resource/client/client.go
  vendor/github.com/tektoncd/hub/api/v1/gen/http/resource/client/encode_decode.go
  vendor/github.com/tektoncd/hub/api/v1/gen/http/resource/client/paths.go
  vendor/github.com/tektoncd/hub/api/v1/gen/http/resource/client/types.go
  vendor/github.com/tektoncd/hub/api/v1/gen/resource/client.go
  vendor/github.com/tektoncd/hub/api/v1/gen/resource/endpoints.go
  vendor/github.com/tektoncd/hub/api/v1/gen/resource/service.go
  vendor/github.com/tektoncd/hub/api/v1/gen/resource/views/view.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, release-note

#1516 fix missing Cursor with interactive start commands
  go.mod
  go.sum
  vendor/github.com/AlecAivazis/survey/v2/README.md
  vendor/github.com/AlecAivazis/survey/v2/_tasks.hcl
  vendor/github.com/AlecAivazis/survey/v2/core/template.go
  vendor/github.com/AlecAivazis/survey/v2/core/write.go
  vendor/github.com/AlecAivazis/survey/v2/go.mod
  vendor/github.com/AlecAivazis/survey/v2/go.sum
  vendor/github.com/AlecAivazis/survey/v2/input.go
  vendor/github.com/AlecAivazis/survey/v2/multiselect.go
  vendor/github.com/AlecAivazis/survey/v2/renderer.go
  vendor/github.com/AlecAivazis/survey/v2/select.go
  vendor/github.com/AlecAivazis/survey/v2/survey.go
  vendor/github.com/AlecAivazis/survey/v2/terminal/runereader.go
  vendor/github.com/AlecAivazis/survey/v2/terminal/runereader_posix.go
  vendor/github.com/AlecAivazis/survey/v2/validate.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL, release-note

#1521 Fix tektoncd docs installation instructions
  docs/README.md
Labels: lgtm, approved, size/S, release-note-none

#1525 Update docs to latest version 0.23.0
  README.md
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: lgtm, approved, size/M, release-note

#1529 Adds namespace where operator is installed
  pkg/version/version.go
Labels: size/XS, lgtm, approved, release-note

#1530 Remove go11modules export instructions in README
  README.md
Labels: size/XS, lgtm, approved, release-note-none

#1526 Add information in README on how to install on Arch
  README.md
  RELEASE_PROCESS.md
Labels: lgtm, approved, size/S, release-note

#1523 ROADMAP.md: update it to reflect 2022 goals
  ROADMAP.md
Labels: lgtm, approved, size/M, release-note-none

#1467 Go compile darwin-arm64 in makefile for m1 macs
  Makefile
Labels: size/XS, lgtm, approved, release-note-none, ok-to-test

#1531 Add tkn taskrun export command
  docs/cmd/tkn_taskrun.md
  docs/cmd/tkn_taskrun_export.md
  docs/man/man1/tkn-taskrun-export.1
  docs/man/man1/tkn-taskrun.1
  pkg/cmd/taskrun/export.go
  pkg/cmd/taskrun/taskrun.go
  pkg/export/export.go
  pkg/export/export_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/vault/sdk/version/cgo.go
Labels: lgtm, approved, size/L, release-note

#1536 Updates the configMap name for Operator version
  pkg/cmd/version/version_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: size/XS, lgtm, approved, release-note

#1540 Add -o name to pipeline start
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=name.golden
Labels: lgtm, approved, size/L, release-note

#1542 This will fix the version command failing for chain and operator
  pkg/version/version.go
Labels: lgtm, approved, size/S, release-note

#1532 fix error while deleting pr without status
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
Labels: lgtm, approved, size/M, release-note

#1544 update version in readme to v0.23.1
  README.md
Labels: lgtm, approved, size/M, release-note

#1545 Bump choco spec to v0.23.1
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: size/XS, lgtm, approved
