Repository tektoncd/cli, pull requests merged in 2022-08, with the labels that each got.

#1557 Allow to use bundle with no kubeconfig
  pkg/cmd/bundle/bundle.go
Labels: lgtm, approved, size/S, release-note-none, ok-to-test

#1572 Adding a check for the set bundle max used in the pipeline controller.
  pkg/bundle/builder.go
  pkg/bundle/builder_test.go
Labels: lgtm, approved, size/L, ok-to-test, release-note

#1675 Bump golangci-lint to v1.47.2 for Go 1.18 support
  Makefile
  tools/go.mod
  tools/go.sum
Labels: lgtm, approved, size/XL, release-note-none, kind/misc

#1679 Clean up all lint issues found by `make check`.
  cmd/docs/generate.go
  cmd/docs/md_docs.go
  pkg/bundle/keychain_test.go
  pkg/bundle/remote_test.go
  pkg/cmd/bundle/list.go
  pkg/cmd/bundle/push.go
  pkg/cmd/bundle/push_test.go
  pkg/cmd/root_test.go
  pkg/cmd/version/version.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/formatted/color_test.go
  pkg/plugins/plugins.go
  pkg/plugins/plugins_test.go
  pkg/pods/fake/stream.go
  test/framework/logs.go
Labels: lgtm, approved, size/M, release-note-none

#1686 Remove v1alpha1 support for task
  pkg/cmd/clustertask/create_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/task/create_test.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/logs.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full.golden
  pkg/cmd/task/testdata/TestTaskDescribe_WithoutNameIfOnlyOneV1beta1TaskPresent.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_all_namespaces.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_all_namespaces_no_headers.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_no_headers.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--param_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--param_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_PodTemplate.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f_v1alpha1.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskV1beta1Describe_Full.golden
  pkg/cmd/task/testdata/task-invalid-v1alpha1.yaml
  pkg/cmd/task/testdata/task-invalid.yaml
  pkg/cmd/task/testdata/task-param-with-invalid-type.yaml
  pkg/cmd/task/testdata/task-v1alpha1.yaml
  pkg/cmd/task/testdata/task.yaml
  pkg/cmd/taskrun/delete_test.go
  pkg/task/task.go
  pkg/task/task_test.go
  pkg/task/tasklastrun_test.go
  pkg/test/builder/unstructured.go
Labels: lgtm, approved, size/XXL, release-note

#1669 Use golang 1.17.3 in contrib/tkn-image/Dockerfile
  contrib/tkn-image/Dockerfile
Labels: size/XS, lgtm, approved, ok-to-test, release-note

#1689 Remove v1alpha1 support for taskrun
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/list_test.go
  pkg/cmd/taskrun/logs_test.go
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-all_in_namespace.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-by_Task_name.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-by_output_as_name.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-empty_list.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-error_from_invalid_namespace.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-filter_taskruns_by_label.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-filter_taskruns_by_label_with_in_query.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-limit_taskruns_greater_than_maximum_case.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-limit_taskruns_negative_case.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-limit_taskruns_returned_to_1.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-limit_taskruns_with_output_flag_set.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-no_mixing_pipelinename_and_labels.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-print_by_template.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-print_in_reverse.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-print_in_reverse_with_output_flag.golden
  pkg/cmd/taskrun/testdata/TestListTaskRuns_v1beta1-print_taskruns_in_all_namespaces.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_WithSpec_custom_timeout.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_WithoutNameIfOnlyOneTaskRunPresent.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_WithoutNameIfOnlyOneV1beta1TaskRunPresent.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_last.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_lastV1beta1.golden
  pkg/log/task_reader.go
  pkg/taskrun/create.go
  pkg/taskrun/get.go
  pkg/taskrun/get_test.go
  pkg/taskrun/list/list.go
  pkg/taskrun/list/list_test.go
  pkg/taskrun/taskrun.go
  pkg/taskrun/watch.go
Labels: lgtm, approved, size/XXL, release-note

#1690 Remove PipelineRun v1alpha1 support
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-Invalid_namespace.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-all_in_namespace.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_output_as_name.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_pipeline_name.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_template.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-filter_pipelineruns_by_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-filter_pipelineruns_by_label_with_in_query.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_greater_than_maximum_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_negative_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_returned_to_1.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_with_output_flag_set.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-no_mixing_pipelinename_and_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_in_reverse.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_in_reverse_with_output_flag.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_pipelineruns_in_all_namespaces.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_last.golden
  pkg/log/pipeline_reader.go
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/pipelinerun/tracker.go
Labels: lgtm, approved, size/XXL, release-note-none
