Repository tektoncd/cli, pull requests merged in 2022-04, with the labels that each got.

#1554 Cancel PipelineRuns using Cancelled status
  pkg/cmd/pipelinerun/cancel.go
Labels: lgtm, approved, size/S, release-note

#1541 Fixes pipelinerun and taskrun deletion with keep flag
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: lgtm, approved, size/M, release-note

#1558 Add vinamra28 as owner
  OWNERS
Labels: size/XS, lgtm, approved, release-note
