Repository tektoncd/cli, pull requests merged in 2022-10, with the labels that each got.

#1732 README.md: add some badges
  README.md
Labels: size/XS, lgtm, approved, release-note-none, kind/misc

#1736 fix taskrun getting deleted of running pipelinerun
  docs/cmd/tkn_taskrun_delete.md
  docs/man/man1/tkn-taskrun-delete.1
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/options/delete.go
Labels: lgtm, approved, size/L, release-note

#1740 Enable CodeQL analsys for CLI
  .github/workflows/codeql-analysis.yml
Labels: lgtm, approved, size/M, release-note-none

#1742 Mark PipelineResource cmds deprecated
  docs/cmd/tkn.md
  docs/man/man1/tkn.1
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/delete.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
  pkg/cmd/pipelineresource/pipelineresource.go
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceDescribe_WithParams.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceDescribe_WithSecretParams.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-All_Namespaces.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-By_template.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-Empty_Pipeline_Resource_by_type.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-Invalid_namespace.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-Multiple_Pipeline_Resource_by_type.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-Multiple_pipeline_resources.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-No_Headers.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-Single_Pipeline_Resource_by_type.golden
  pkg/cmd/pipelineresource/testdata/TestPipelineResourceList-Single_pipeline_resource.golden
Labels: lgtm, approved, size/M, release-note

#1746 update go and golangci-lint version
  tekton/release-pipeline.yml
Labels: size/XS, lgtm, approved, release-note

#1747 Add releases.md for the CLI
  README.md
Labels: size/XS, lgtm, approved, release-note-none

#1748 Update README for v0.27.0
  README.md
Labels: lgtm, approved, size/M, release-note

#1752 Actually add a releases.md
  releases.md
Labels: lgtm, approved, size/M, release-note-none

#1751 Add timestamps flag to show PipelineRun log with timestamps
  docs/cmd/tkn_pipelinerun_logs.md
  docs/man/man1/tkn-pipelinerun-logs.1
  pkg/cmd/pipelinerun/logs.go
  pkg/log/reader.go
  pkg/log/task_reader.go
  pkg/options/logs.go
  pkg/pods/container.go
  pkg/pods/container_test.go
Labels: lgtm, approved, size/M, ok-to-test, release-note

#1745 Update .goreleaser.yml
  .goreleaser.yml
Labels: size/XS, lgtm, approved, release-note-none, ok-to-test

#1761 Update choco package to v0.27.0
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: size/XS, lgtm, approved, release-note-none

#1755 Add timestamps flags to all pipeline resources that have logs command
  docs/cmd/tkn_clustertask_logs.md
  docs/cmd/tkn_pipeline_logs.md
  docs/cmd/tkn_task_logs.md
  docs/cmd/tkn_taskrun_logs.md
  docs/man/man1/tkn-clustertask-logs.1
  docs/man/man1/tkn-pipeline-logs.1
  docs/man/man1/tkn-task-logs.1
  docs/man/man1/tkn-taskrun-logs.1
  pkg/cmd/clustertask/logs.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/task/logs.go
  pkg/cmd/taskrun/logs.go
Labels: lgtm, approved, size/M, ok-to-test, release-note
