Repository tektoncd/cli, pull requests merged in 2022-12, with the labels that each got.

#1807 Remove k8s client validity check from pkg/flags
  pkg/flags/flags.go
Labels: size/XS, lgtm, approved, ok-to-test, release-note

#1831 Fix e2e test broken
  test/e2e/clustertask/start_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/pipeline/start_test.go
  test/e2e/task/start_test.go
  test/resources/output-pipelinerun.yaml
  test/resources/pipeline.yaml
  test/resources/read-file-clustertask.yaml
  test/resources/read-file.yaml
Labels: lgtm, approved, size/M, release-note

#1836 Fix pipeline version to v0.42.0 in e2e
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/tracker.go
  test/e2e-common.sh
  vendor/github.com/tektoncd/pipeline/pkg/status/status.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, release-note

#1794 Add support to pass CSI workspace
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  docs/reference/cmd/pipeline_start.md
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/task/start.go
  pkg/formatted/workspace.go
  pkg/formatted/workspace_test.go
  pkg/workspaces/testdata/csi-typo.yaml
  pkg/workspaces/testdata/csi.yaml
  pkg/workspaces/workspaces.go
  pkg/workspaces/workspaces_test.go
Labels: lgtm, approved, size/L, release-note
