Repository tektoncd/cli, pull requests merged in 2022-07, with the labels that each got.

#1629 Fix eventlistener e2e tests broken due to upgrading Triggers to v0.20.1
  test/cli/cli.go
  test/e2e-common.sh
  test/e2e/clustertask/start_test.go
  test/e2e/eventListener/eventListener_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/pipelinerun/pipelinerun_test.go
  test/e2e/plugin/plugin_test.go
  test/e2e/task/start_test.go
  test/framework/helper.go
  test/resources/eventlistener/eventlistener.yaml
  test/resources/eventlistener/eventlistener_v1beta1.yaml
Labels: lgtm, approved, size/L, release-note-none, kind/misc

#1632 Remove conditions from README
  README.md
Labels: size/XS, lgtm, approved, release-note

#1631 [Packaging] Force building debian package as gzip
  tekton/debbuild/control/rules
  tekton/debbuild/control/source/options
Labels: size/XS, lgtm, approved, release-note

#1617 Add support for PipelineRun minimal embedded status
  pkg/cmd/pipelinerun/logs_test.go
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/pipelinerun/tracker.go
  pkg/pipelinerun/tracker_test.go
  test/e2e-tests.sh
  tools/go.mod
  vendor/github.com/tektoncd/pipeline/test/diff/print.go
  vendor/github.com/tektoncd/pipeline/test/parse/yaml.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, size/XL, release-note, kind/tep

#1640 Remove the rest of reference to Conditions 🥸
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_WithoutNameIfOnlyOnePipelinePresent.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_task_conditions.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_results.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_taskSpec.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribeV1beta1_with_workspaces.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_multiple_v1alpha1_pipelineruns.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_multiple_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_resource_param_run.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_run.golden
  pkg/formatted/conditions.go
  pkg/formatted/conditions_test.go
  test/builder/builder.go
  test/framework/clients.go
Labels: lgtm, approved, size/L, release-note-none, kind/misc

#1601 Show Timeouts in PipelineRun describe cmd and deprecate Timeout
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribeWithTimeouts.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_cancelled_pipelinerun.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_cancelled_pipelinerun_multiple_taskrun.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_custom_timeout.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_failed.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_failed_withoutPRCondition.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_failed_withoutTRCondition.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_last.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_multiple_taskrun_ordering.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_multiple_taskrun_without_status.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_no_resourceref.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_only_taskrun.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_with_resources_taskrun.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_without_start_time.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_without_tr_start_time.golden
  pkg/formatted/color.go
  pkg/formatted/color_test.go
  pkg/pipelinerun/description/description.go
Labels: lgtm, approved, size/L, release-note

#1566 feat: display annotations for describe command
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/TestClusterTaskDescribe_with_annotations.golden
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_annotations.golden
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_with_annotations.golden
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_with_annotations.golden
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_with_annotations.golden
  pkg/formatted/description.go
  pkg/formatted/description_test.go
  pkg/pipelinerun/description/description.go
  pkg/taskrun/description/description.go
Labels: lgtm, approved, size/L, ok-to-test, release-note

#1644 Switch to prefered quilt packaging format.
  tekton/debbuild/control/source/format
Labels: size/XS, lgtm, approved, release-note

#1642 Add different timeout flags for Pipeline start cmd
  docs/cmd/tkn_pipeline_start.md
  docs/man/man1/tkn-pipeline-start.1
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_--timeout_specified_(deprecated).golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--pipeline-timeout,_--tasks-timeout,_--finally-timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--pipeline-timeout,_--tasks-timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--pipeline-timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineV1beta1Start_ExecuteCommand-Dry_Run_with_--timeout_specified_(deprecated).golden
Labels: lgtm, approved, size/L, release-note

#1651 Update README for v0.25.0
  README.md
Labels: lgtm, approved, size/M, release-note-none

#1652 Update chocolatey package to 0.25.0
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: size/XS, lgtm, approved, release-note-none

#1654 Fix creating debian packages with latest debhelpers
  tekton/debbuild/control/rules
Labels: size/XS, lgtm, approved, release-note

#1658 Fix e2e test by converting to v1beta1 resources
  test/builder/builder.go
  test/builder/sort.go
  test/builder/validate.go
  test/e2e/clustertask/start_test.go
  test/e2e/eventListener/eventListener_test.go
  test/e2e/pipeline/pipeline_test.go
  test/e2e/task/start_test.go
  test/framework/clients.go
  test/resources/cancel/pipeline-cancel.yaml
  test/resources/cancel/task-cancel.yaml
  test/resources/clustertask-with-optional-workspace.yaml
  test/resources/eventlistener/eventlistener.yaml
  test/resources/output-pipelinerun.yaml
  test/resources/pipeline-with-workspace.yaml
  test/resources/pipeline.yaml
  test/resources/read-file-clustertask.yaml
  test/resources/read-file.yaml
  test/resources/task-volume.yaml
  test/resources/task-with-workspace.yaml
  test/wait/helper-wait.go
  test/wait/wait.go
Labels: lgtm, approved, size/L, release-note

#1656 Fix debbuilds by pointing to build directory
  README.md
  tekton/debbuild/control/rules
Labels: size/XS, lgtm, approved, release-note-none

#1653 Removed apt-key for deb-based install instructions
  docs/README.md
Labels: size/XS, lgtm, approved, ok-to-test, release-note
