Repository tektoncd/cli, pull requests merged in 2022-06, with the labels that each got.

#1579 Add dependabot to the repository
  .github/dependabot.yml
Labels: size/XS, lgtm, approved, release-note-none

#1587 Improve `tkn chain` log format
  pkg/chain/chain.go
Labels: lgtm, approved, size/S, release-note

#1578 Fix --ignore-running not working with -p/-t in delete cmd
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: lgtm, approved, size/XL, release-note

#1588 Ignore zap logger sync error
  pkg/chain/chain.go
Labels: size/XS, lgtm, approved, release-note-none

#1586 Add label dependabot PRs ok-to-test…
  .github/dependabot.yml
Labels: size/XS, lgtm, approved, release-note-none

#1590 update release script compatible with go 1.17
  tekton/release-pipeline-run.yml
  tekton/release-pipeline.yml
  tekton/release.sh
Labels: lgtm, approved, size/S, release-note

#1589 Fix `tkn chains signature/payload` by version bump
  go.mod
  go.sum
  vendor/github.com/tektoncd/chains/pkg/chains/formats/intotoite6/buildconfig.go
  vendor/github.com/tektoncd/chains/pkg/chains/storage/pubsub/pubsub.go
  vendor/github.com/tektoncd/chains/pkg/chains/storage/tekton/tekton.go
  vendor/modules.txt
Labels: lgtm, approved, size/S, release-note-none

#1592 fix unit-test in release pipeline
  tekton/release-pipeline.yml
Labels: size/XS, lgtm, approved, release-note

#1603 Update chocolatey package to 0.24.0
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: size/XS, lgtm, approved, release-note-none

#1604 Update README for 0.24.0
  README.md
Labels: lgtm, approved, size/M, release-note-none

#1602 Use binary for building rpms
  tekton/rpmbuild/build.sh
  tekton/rpmbuild/tekton.spec
Labels: lgtm, approved, size/XL, release-note

#1621 Remove the condition subcommand.
  Makefile
  docs/cmd/tkn.md
  docs/cmd/tkn_condition.md
  docs/cmd/tkn_condition_delete.md
  docs/cmd/tkn_condition_describe.md
  docs/cmd/tkn_condition_list.md
  docs/man/man1/tkn-condition-delete.1
  docs/man/man1/tkn-condition-describe.1
  docs/man/man1/tkn-condition-list.1
  docs/man/man1/tkn-condition.1
  docs/man/man1/tkn.1
  pkg/cmd/condition/condition.go
  pkg/cmd/condition/condition_test.go
  pkg/cmd/condition/delete.go
  pkg/cmd/condition/delete_test.go
  pkg/cmd/condition/describe.go
  pkg/cmd/condition/describe_test.go
  pkg/cmd/condition/list.go
  pkg/cmd/condition/list_test.go
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_command_and_arg.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_command_and_arg_with_output.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_script.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_full_with_script_with_output.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_with_one_resource_param.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-condition_describe_without_resource_param.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-invalid_condition_name.golden
  pkg/cmd/condition/testdata/TestConditionDescribe-invalid_namespace.golden
  pkg/cmd/condition/testdata/TestConditionList-Conditions_from_all_namespaces.golden
  pkg/cmd/condition/testdata/TestConditionList-Failed_to_list_condition_resources.golden
  pkg/cmd/condition/testdata/TestConditionList-Failed_to_list_condition_resources_with_specify_output_flag.golden
  pkg/cmd/condition/testdata/TestConditionList-Found_conditions.golden
  pkg/cmd/condition/testdata/TestConditionList-Found_no_conditions.golden
  pkg/cmd/condition/testdata/TestConditionList-Invalid_Namespace.golden
  pkg/cmd/condition/testdata/TestConditionList-List_conditions_from_all_namespaces_without_headers.golden
  pkg/cmd/condition/testdata/TestConditionList-List_conditions_without_headers.golden
  pkg/cmd/condition/testdata/TestConditionList-No_conditions_found_in_all_namespaces.golden
  pkg/cmd/condition/testdata/TestConditionList-Specify_output_flag.golden
  pkg/cmd/root.go
  pkg/cmd/testdata/TestPluginList.golden
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-plugin/process_posix.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-rootcerts/rootcerts_base.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-secure-stdlib/mlock/mlock_unavail.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-secure-stdlib/mlock/mlock_unix.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-sockaddr/ifaddrs.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-sockaddr/route_info_android.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-sockaddr/route_info_bsd.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-sockaddr/route_info_default.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-sockaddr/route_info_linux.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: kind/feature, lgtm, approved, size/XXL, release-note

#1626 Fix a few tests which failed when run individually
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_using_--filename_v1alpha1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand-Dry_Run_with_output=json_-f_v1alpha1.golden
  pkg/cmd/pipeline/testdata/pipeline-v1alpha1.yaml
Labels: lgtm, approved, size/M, release-note-none
