Repository tektoncd/cli, pull requests merged in 2022-11, with the labels that each got.

#1772 Add few reference notes in debbuild readme
  tekton/debbuild/README.md
Labels: lgtm, approved, size/S, release-note-none

#1575 Add *experimental* commands support
  docs/cmd/tkn_bundle_list.md
  pkg/cli/prerun/prerun.go
  pkg/cmd/bundle/bundle.go
  pkg/cmd/bundle/list.go
  pkg/cmd/bundle/list_test.go
  pkg/cmd/chain/chain.go
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertriggerbinding/clustertriggerbinding.go
  pkg/cmd/eventlistener/eventlistener.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipelineresource/pipelineresource.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/root.go
  pkg/cmd/task/task.go
  pkg/cmd/taskrun/taskrun.go
  pkg/cmd/testdata/TestPluginList.golden
  pkg/cmd/triggerbinding/triggerbinding.go
  pkg/cmd/triggertemplate/triggertemplate.go
Labels: kind/feature, lgtm, approved, size/L, release-note

#1754 [TEP-0093] Add sign and verify as experiment subcommands to tekton cli
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_sign.md
  docs/cmd/tkn_pipeline_verify.md
  docs/cmd/tkn_task.md
  docs/cmd/tkn_task_sign.md
  docs/cmd/tkn_task_verify.md
  docs/man/man1/tkn-pipeline-sign.1
  docs/man/man1/tkn-pipeline-verify.1
  docs/man/man1/tkn-pipeline.1
  docs/man/man1/tkn-task-sign.1
  docs/man/man1/tkn-task-verify.1
  docs/man/man1/tkn-task.1
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/sign.go
  pkg/cmd/pipeline/sign_test.go
  pkg/cmd/pipeline/testdata/cosign.key
  pkg/cmd/pipeline/testdata/cosign.pub
  pkg/cmd/pipeline/testdata/signed.yaml
  pkg/cmd/pipeline/verify.go
  pkg/cmd/pipeline/verify_test.go
  pkg/cmd/task/sign.go
  pkg/cmd/task/sign_test.go
  pkg/cmd/task/task.go
  pkg/cmd/task/testdata/cosign.key
  pkg/cmd/task/testdata/cosign.pub
  pkg/cmd/task/testdata/signed.yaml
  pkg/cmd/task/verify.go
  pkg/cmd/task/verify_test.go
  pkg/trustedresources/sign.go
  pkg/trustedresources/sign_test.go
  pkg/trustedresources/verify.go
  pkg/trustedresources/verify_test.go
Labels: kind/feature, lgtm, approved, size/XXL, release-note

#1806 Bump chocolatey package to 0.28.0
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: size/XS, lgtm, approved, release-note-none

#1805 Bump version to v0.28.0 in README and releases.md
  README.md
  releases.md
Labels: lgtm, approved, size/M, release-note-none
