Repository tektoncd/cli, pull requests merged in 2022-01, with the labels that each got.

#1398 Add a pipeline export command
  docs/cmd/tkn_pipeline.md
  docs/cmd/tkn_pipeline_export.md
  docs/man/man1/tkn-pipeline-export.1
  docs/man/man1/tkn-pipeline.1
  pkg/cmd/pipeline/export.go
  pkg/cmd/pipeline/pipeline.go
  pkg/export/export.go
  pkg/export/export_test.go
Labels: lgtm, approved, size/L, release-note

#1479 Handle graceful termination of Pipeline
  docs/cmd/tkn_pipelinerun_cancel.md
  docs/man/man1/tkn-pipelinerun-cancel.1
  pkg/cmd/pipelinerun/cancel.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/pipelinerun/pipelinerun.go
Labels: lgtm, approved, size/L, release-note

#1486 Adds operator verison in output of `tkn version` command
  pkg/cmd/version/testdata/TestGetVersions-deployment_with_pipeline,_triggers,_dashboard_and_operator_installed.golden
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: lgtm, approved, size/L, release-note

#1482 Show all cancelled taskruns in message section
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_cancelled_pipelinerun_multiple_taskrun.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_failed.golden
  pkg/pipelinerun/description/description.go
  pkg/pipelinerun/description/description_test.go
Labels: lgtm, approved, size/L, release-note-none

#1465 Skips to ask specifications for optional workspace
  docs/cmd/tkn_clustertask_start.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_task_start.md
  docs/man/man1/tkn-clustertask-start.1
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-task-start.1
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/options/start.go
Labels: lgtm, approved, size/L, release-note

#1490 Bump go mod version to 1.16
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, release-note

#1491 Bump Tekton Hub CLI to latest
  go.mod
  go.sum
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/get_resource_version.go
  vendor/github.com/tektoncd/hub/api/pkg/cli/hub/search.go
  vendor/modules.txt
Labels: lgtm, approved, size/S, release-note-none

#1492 Bump deps
  go.mod
  go.sum
  pkg/cmd/clustertriggerbinding/delete_test.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete_test.go
  pkg/test/helpers.go
  third_party/VENDOR-LICENSE/knative.dev/eventing/pkg/reconciler/source/LICENSE
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/param_context.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/event_listener_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/event_listener_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/event_listener_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_binding_validation.go
  vendor/github.com/tektoncd/triggers/pkg/reconciler/eventlistener/resources/config.go
  vendor/github.com/tektoncd/triggers/pkg/reconciler/eventlistener/resources/container.go
  vendor/github.com/tektoncd/triggers/pkg/reconciler/eventlistener/resources/custom.go
  vendor/github.com/tektoncd/triggers/pkg/reconciler/eventlistener/resources/deployment.go
  vendor/github.com/tektoncd/triggers/pkg/reconciler/eventlistener/resources/meta.go
  vendor/github.com/tektoncd/triggers/pkg/reconciler/eventlistener/resources/service.go
  vendor/github.com/tektoncd/triggers/test/controller.go
  vendor/github.com/tektoncd/triggers/test/e2e-tests-examples.sh
  vendor/github.com/tektoncd/triggers/test/e2e-tests-yaml.sh
  vendor/knative.dev/eventing/AUTHORS
  vendor/knative.dev/eventing/LICENSE
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/filtered/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/filtered/service.go
  vendor/knative.dev/pkg/reconciler/testing/actions.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/events.go
  vendor/knative.dev/pkg/reconciler/testing/generate_name_reactor.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/reconciler/testing/util.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, release-note

#1493 update golangci-lint version
  tekton/release-pipeline.yml
Labels: size/XS, lgtm, approved, release-note

#1494 update go build and test
  tekton/release-pipeline.yml
Labels: size/XS, lgtm, approved, release-note
