Repository tektoncd/cli, pull requests merged in 2022-09, with the labels that each got.

#1694 Remove v1alpha1 support
  pkg/clustertask/clustertask_test.go
  pkg/cmd/bundle/list_test.go
  pkg/cmd/clustertask/start.go
  pkg/cmd/pipelineresource/create.go
  pkg/cmd/pipelineresource/create_test.go
  pkg/cmd/pipelineresource/delete_test.go
  pkg/cmd/pipelineresource/describe.go
  pkg/cmd/pipelineresource/describe_test.go
  pkg/cmd/pipelineresource/list.go
  pkg/cmd/pipelineresource/list_test.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/triggertemplate/describe_test.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_AutoSelect.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_NoParams.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_ParamsToResourceTemplate.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOneParam.golden
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithOutputYaml.golden
  pkg/cmd/version/version_test.go
  pkg/file/file_test.go
  pkg/file/testdata/task.yaml
  pkg/options/start.go
  pkg/pipelineresource/sort/by_namespace.go
  pkg/pipelineresource/sort/by_namespace_test.go
  pkg/pipelineresource/sort/by_type_and_name.go
  pkg/pipelineresource/sort/by_type_and_name_test.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/pods/container_test.go
  pkg/pods/pod_test.go
  pkg/suggestion/suggest_test.go
  pkg/task/task.go
  pkg/taskrun/create.go
  pkg/test/builder/unstructured.go
  pkg/test/dynamic/clientset/tekton.go
  pkg/test/dynamic/dynamictestclient.go
  pkg/test/helpers.go
  pkg/version/version_test.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/clustertask/clustertask.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/clustertask/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/pipeline/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/pipeline/pipeline.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/pipelinerun/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/pipelinerun/pipelinerun.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/task/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/task/task.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/taskrun/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1alpha1/taskrun/taskrun.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/build_logs.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/clients.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/controller.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/doc.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/secret.go
  vendor/github.com/tektoncd/pipeline/test/v1alpha1/wait.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, release-note

#1693 Add qps and bursts same like kubectl
  pkg/cli/params.go
Labels: size/XS, lgtm, approved, release-note

#1699 Refactor create operation in cli
  pkg/clustertask/clustertask.go
  pkg/pipelinerun/pipelinerun.go
  pkg/task/task.go
Labels: lgtm, approved, size/S, release-note

#1701 Increase workspace size for release pipeline
  tekton/volume-claim-template.yml
Labels: size/XS, lgtm, approved, release-note

#1700 Update docs to v0.26.0
  README.md
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: lgtm, approved, size/M, release-note

#1708 Fix incomplete TaskRuns being deleted when --ignore-running=true
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: lgtm, approved, size/L, ok-to-test, release-note

#1714 Make zsh completion usable without generating file
  docs/cmd/tkn_completion.md
  docs/man/man1/tkn-completion.1
  pkg/cmd/completion/completion.go
  pkg/cmd/completion/completion_test.go
Labels: lgtm, approved, size/M, release-note

#1717 Align client-go to rest of K8s dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S, ok-to-test, release-note

#1719 OWNERS: update file according to "current" active maintainers
  OWNERS
Labels: size/XS, lgtm, approved, release-note-none

#1724 Fix bundle push authentication error
  pkg/bundle/flags.go
Labels: size/XS, lgtm, approved, release-note-none, ok-to-test

#1725 Query PipelineResources only if needed
  pkg/cmd/pipeline/start.go
Labels: size/XS, lgtm, approved, release-note-none

#1727 Use tkn root comand to get the name of the tkn cli
  pkg/suggestion/suggest.go
Labels: size/XS, lgtm, approved, release-note

#1726 Fix the race condition on closing eventC
  pkg/pods/pod.go
Labels: lgtm, approved, size/M, ok-to-test, release-note
