Repository tektoncd/cli, pull requests merged in 2022-02, with the labels that each got.

#1496 update goreleaser
  tekton/release.sh
Labels: size/XS, lgtm, approved, release-note

#1497 update goreleaser config
  .goreleaser.yml
Labels: size/XS, lgtm, approved, release-note

#1498 update tkn v0.22.0
  README.md
Labels: lgtm, approved, size/M, release-note

#1499 Update tkn chocolatey package to v0.22.0
  .gitignore
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
Labels: lgtm, approved, size/S, release-note-none

#1503 Use ubuntu-rolling to build package
  README.md
  tekton/debbuild/container/Dockerfile
Labels: size/XS, lgtm, approved, release-note

#1505 Make `vendor` a PHONY target
  Makefile
Labels: size/XS, lgtm, approved, release-note-none

#1500 Add export option for pipelinerun
  docs/cmd/tkn_pipelinerun.md
  docs/cmd/tkn_pipelinerun_export.md
  docs/man/man1/tkn-pipelinerun-export.1
  docs/man/man1/tkn-pipelinerun.1
  pkg/cmd/pipeline/export.go
  pkg/cmd/pipelinerun/export.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/export/export.go
  pkg/export/export_test.go
Labels: lgtm, approved, size/L, release-note

#1484 Checked existence of resources before deletion
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/delete_test.go
  pkg/cmd/clustertriggerbinding/delete.go
  pkg/cmd/clustertriggerbinding/delete_test.go
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/eventlistener/delete_test.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggerbinding/delete_test.go
  pkg/cmd/triggertemplate/delete.go
  pkg/cmd/triggertemplate/delete_test.go
Labels: lgtm, approved, size/XL, ok-to-test, release-note

#1513 pass rest config when create tkn clients,fix the default QPS is to low(QPS is 5),can improve the concurrent #1512
  pkg/cli/interface.go
  pkg/cli/params.go
  pkg/test/params.go
Labels: lgtm, approved, size/S, ok-to-test, release-note
