Repository tektoncd/cli, pull requests merged in 2023-01, with the labels that each got.

#1839 fix trusted resources docs error
  docs/cmd/tkn_pipeline_sign.md
  docs/cmd/tkn_pipeline_verify.md
  docs/cmd/tkn_task_sign.md
  docs/cmd/tkn_task_verify.md
  docs/man/man1/tkn-pipeline-sign.1
  docs/man/man1/tkn-pipeline-verify.1
  docs/man/man1/tkn-task-sign.1
  docs/man/man1/tkn-task-verify.1
  pkg/cmd/pipeline/sign.go
  pkg/cmd/pipeline/verify.go
  pkg/cmd/task/sign.go
  pkg/cmd/task/verify.go
Labels: lgtm, approved, size/S, kind/documentation, release-note

#1846 Bump readme to point to latest release v0.29.0
  README.md
  choco/tools/chocolateyinstall.ps1
  releases.md
Labels: lgtm, approved, size/M, release-note-none

#1857 Update choco nuspec for v0.29.0
  choco/tektoncd-cli.nuspec
Labels: size/XS, lgtm, approved, release-note-none

#1873 Add v1 support for task and pipeline list
  pkg/actions/list.go
  pkg/cmd/clustertask/create_test.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/export.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/testdata/TestPipelineList_only_pipelines_all_namespaces_no_headers_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineList_only_pipelines_all_namespaces_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineList_only_pipelines_no_headers_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineList_only_pipelines_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelinesList_latest_run_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelinesList_with_single_run_v1beta1.golden
  pkg/cmd/pipelinerun/logs_test.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/task/describe.go
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/logs.go
  pkg/cmd/task/logs_test.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/task.go
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_all_namespaces_no_headers_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_all_namespaces_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_no_headers_v1beta1.golden
  pkg/cmd/task/testdata/TestTaskList_Only_Tasks_v1beta1.golden
  pkg/cmd/taskrun/delete_test.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/task/task.go
  pkg/task/task_test.go
  pkg/task/tasklastrun_test.go
  pkg/test/builder/unstructured.go
  pkg/test/controller.go
  pkg/test/dynamic/clientset/tekton.go
  pkg/test/dynamic/dynamictestclient.go
  pkg/test/helpers.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/pipeline/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/pipeline/pipeline.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/pipelinerun/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/pipelinerun/pipelinerun.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/task/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/task/task.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/taskrun/fake/fake.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/informers/pipeline/v1/taskrun/taskrun.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, release-note
