Repository tektoncd/cli, pull requests merged in 2023-04, with the labels that each got.

#1974 Fix tkn tr delete command not deleting trs of completed pr
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: lgtm, approved, size/L, release-note

#1983 Remove PipelineResource support in clustertask
  pkg/cmd/clustertask/start.go
  pkg/cmd/clustertask/start_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_Run_with_--prefix-name_and_--last_v1beta1.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_Run_with_--prefix-name_v1beta1.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_--last.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_--timeout_v1beta1.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_PodTemplate.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTask_Start-Dry_run_with_no_output_v1beta1.golden
Labels: lgtm, approved, size/L, release-note

#1985 Adapt for changes in TEP-0100
  pkg/cmd/pipelinerun/logs_test.go
  test/builder/validate.go
Labels: lgtm, approved, size/M, release-note-none, ok-to-test

#1984 Remove PipelineResource support in task
  pkg/cmd/task/start.go
  pkg/cmd/task/start_test.go
  pkg/cmd/task/start_v1_test.go
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--param_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_PodTemplate.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--param_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--timeout_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_-f.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_PodTemplate.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json.golden
  pkg/cmd/task/testdata/TestTaskStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json_-f.golden
  pkg/cmd/task/testdata/task-param-with-invalid-type.yaml
  pkg/cmd/task/testdata/task.yaml
Labels: lgtm, approved, size/XXL, release-note

#1988 Remove PipelineResource support in pipeline
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipeline/start_v1_test.go
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_using_--filename_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_--pipeline-timeout,_--tasks-timeout,_--finally-timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_--pipeline-timeout,_--tasks-timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_--pipeline-timeout_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_--timeout_specified_(deprecated).golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_no_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_--use-param-defaults_and_specified_params.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_PodTemplate.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_only_--dry-run_specified.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_output=json_-f_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineStart_ExecuteCommand_v1beta1-Dry_Run_with_output=name.golden
  pkg/cmd/pipeline/testdata/pipeline-invalid.yaml
  pkg/cmd/pipeline/testdata/pipeline-parameter-with-invalid-type.yaml
  pkg/cmd/pipeline/testdata/pipeline.yaml
Labels: lgtm, approved, size/XXL, release-note

#1987 remove e2e pipeline resource tests
  test/e2e/resource/create_test.go
  test/e2e/resource/testdata/TestCreateGitResourceInteractively-list_single_pipeline_resource_of_git_type.golden
  test/e2e/resource/testdata/TestCreateImageResourceInteractively-list_single_pipeline_resource_of_image_type.golden
  test/e2e/resource/testdata/TestCreatePullRequestResourceInteractively-list_single_pipeline_resource_of_pullrequest_type.golden
  test/e2e/resource/testdata/TestCreateStorageResourceInteractively-list_single_pipeline_resource_of_storage_type.golden
Labels: lgtm, approved, size/L, release-note

#1994 Remove input and output resource in clustertask describe command
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/describe_test.go
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_clustertask_missing_param_default_one_of_everything.golden
  pkg/cmd/clustertask/testdata/Test_ClusterTaskDescribe-Describe_full_clustertask_multiple_taskruns.golden
Labels: lgtm, approved, size/L, release-note

#1996 Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/bundle/builder_test.go
  pkg/bundle/parser_test.go
  pkg/bundle/reader_test.go
  pkg/cmd/bundle/push_test.go
  pkg/cmd/clustertask/start.go
  pkg/file/file_test.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL, release-note-none, ok-to-test

#2000 Remove docs related to PipelineResource
  README.md
  docs/cmd/tkn_pipeline_start.md
  docs/cmd/tkn_resource.md
  docs/cmd/tkn_resource_create.md
  docs/cmd/tkn_resource_delete.md
  docs/cmd/tkn_resource_describe.md
  docs/cmd/tkn_resource_list.md
  docs/man/man1/tkn-pipeline-start.1
  docs/man/man1/tkn-resource-create.1
  docs/man/man1/tkn-resource-delete.1
  docs/man/man1/tkn-resource-describe.1
  docs/man/man1/tkn-resource-list.1
  docs/man/man1/tkn-resource.1
  docs/reference/cmd/pipeline_start.md
Labels: lgtm, approved, size/XL, release-note

#2005 Remove PipelineResource in the describe command test
  pkg/cmd/pipeline/describe_test.go
  pkg/cmd/pipeline/export_test.go
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_WithoutNameIfOnlyOnePipelinePresent_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_OptionalWorkspaces_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_multiple_pipelineruns_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_results_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_multiple_resource_param_run_output_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_multiple_resource_param_run_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_spec_resource_param_run_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineDescribe_with_workspaces_v1beta1.golden
  pkg/cmd/pipeline/testdata/TestPipelineExport_v1beta1.golden
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/pipelinerun/describe_test.go
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribeWithSkippedTasks_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribeWithTimeouts_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_last_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_no_resourceref_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_taskrun_with_no_status_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_with_resources_taskrun_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_with_results_v1beta1.golden
  pkg/cmd/pipelinerun/testdata/TestPipelineRunDescribe_with_workspaces_v1beta1.golden
  pkg/cmd/task/describe_test.go
  pkg/cmd/task/testdata/TestTaskDescribe_Full_v1beta1.golden
  pkg/cmd/taskrun/describe_test.go
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_no_resourceref_v1beta1.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_only_taskrun_v1beta1.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_sidecar_status_defaults_and_failures_v1beta1.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_pending_one_sidecar_v1beta1.golden
  pkg/cmd/taskrun/testdata/TestTaskRunDescribe_step_status_running_multiple_sidecars_v1beta1.golden
  pkg/cmd/triggertemplate/describe_test.go
  pkg/cmd/triggertemplate/testdata/TestTriggerTemplateDescribe_WithMultipleResourceTemplate.golden
  pkg/options/describe.go
  pkg/options/describe_test.go
  pkg/options/resource_names.go
  pkg/test/dynamic/clientset/tekton.go
  tekton/release.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/resources/eventlistener/eventlistener.yaml
  test/resources/eventlistener/eventlistener_log.yaml
  test/resources/eventlistener/eventlistener_v1beta1.yaml
  test/resources/eventlistener/eventlistener_v1beta1_log.yaml
Labels: lgtm, approved, size/XL, release-note
