Repository tektoncd/cli, pull requests merged in 2023-02, with the labels that each got.

#1875 Fix for taskrun list command not working
  pkg/cmd/bundle/bundle.go
  pkg/cmd/bundle/list.go
  pkg/cmd/bundle/push.go
  pkg/cmd/taskrun/list.go
  pkg/flags/flags.go
Labels: lgtm, approved, size/S, release-note

#1879 Update Release Notes and Chocolatey to 0.29.1
  README.md
  choco/tools/chocolateyinstall.ps1
  releases.md
Labels: lgtm, approved, size/M, release-note-none

#1892 Fixes List command for task and pipeline
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/list_test.go
  pkg/cmd/pipeline/testdata/TestPipelineList_in_all_namespaces_with_output_yaml_flag.golden
  pkg/cmd/task/list.go
  pkg/cmd/task/list_test.go
  pkg/cmd/task/testdata/TestTaskList_in_all_namespaces_with_output_yaml_flag.golden
Labels: lgtm, approved, size/L, release-note

#1899 Enable dependabot on tools and run daily
  .github/dependabot.yml
Labels: lgtm, approved, size/S, release-note, kind/misc

#1905 remove kubernetes requirements for sign and verify
  pkg/cmd/pipeline/sign.go
  pkg/cmd/pipeline/verify.go
  pkg/cmd/task/sign.go
  pkg/cmd/task/verify.go
Labels: size/XS, lgtm, approved, release-note

#1912 Not use io/ioutil package anymore
  pkg/cmd/pipeline/sign.go
  pkg/cmd/pipeline/sign_test.go
  pkg/cmd/pipeline/verify.go
  pkg/cmd/task/sign.go
  pkg/cmd/task/sign_test.go
  pkg/cmd/task/verify.go
  pkg/trustedresources/sign_test.go
  third_party/VENDOR-LICENSE/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
Labels: lgtm, approved, size/M, release-note

#1909 Fix the EL logging e2e test
  test/e2e/eventListener/eventListener_test.go
  test/resources/eventlistener/eventlistener_log.yaml
  test/resources/eventlistener/eventlistener_v1beta1_log.yaml
Labels: lgtm, approved, size/L, release-note-none

#1915 Bump pipelinerun list command for v1 CRDs
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/describe.go
  pkg/cmd/pipeline/list.go
  pkg/cmd/pipeline/logs.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/start.go
  pkg/cmd/pipeline/start_test.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/describe.go
  pkg/cmd/pipelinerun/export.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/pipelinerun/list_test.go
  pkg/cmd/pipelinerun/logs.go
  pkg/cmd/pipelinerun/pipelinerun.go
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-Invalid_namespace.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-all_in_namespace.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_output_as_name.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_pipeline_name.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-by_template.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-filter_pipelineruns_by_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-filter_pipelineruns_by_label_with_in_query.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_greater_than_maximum_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_negative_case.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_returned_to_1.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-limit_pipelineruns_with_output_flag_set.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-no_mixing_pipelinename_and_label.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_in_reverse.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_in_reverse_with_output_flag.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_pipelineruns_in_all_namespaces.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_pipelineruns_in_all_namespaces_without_headers.golden
  pkg/cmd/pipelinerun/testdata/TestListPipelineRuns-print_pipelineruns_without_headers.golden
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipelinelastrun.go
  pkg/pipeline/pipelinelastrun_test.go
  pkg/pipelinerun/pipelinerun.go
  pkg/pipelinerun/pipelinerun_test.go
  pkg/pipelinerun/sort/by_namespace.go
  pkg/pipelinerun/sort/by_namespace_test.go
  pkg/pipelinerun/sort/by_start_time.go
  pkg/pipelinerun/sort/by_start_time_test.go
  test/e2e/pipeline/pipeline_test.go
Labels: lgtm, approved, size/XXL, release-note

#1906 Add v1 support for taskrun and pipelinerun cancel
  pkg/actions/patch.go
  pkg/cmd/pipelinerun/cancel_test.go
  pkg/cmd/taskrun/cancel.go
  pkg/cmd/taskrun/cancel_test.go
  pkg/pipelinerun/pipelinerun.go
  pkg/taskrun/patch.go
Labels: lgtm, approved, size/XXL, release-note

#1917 Update clustertask list refactoring
  pkg/clustertask/clustertask.go
  pkg/clustertask/clustertask_test.go
  pkg/cmd/clustertask/clustertask.go
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertask/describe.go
  pkg/cmd/clustertask/list.go
  pkg/cmd/clustertask/logs.go
Labels: lgtm, approved, size/M, release-note

#1918 Add v1 support for delete command
  pkg/cmd/pipeline/delete_test.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/task/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: lgtm, approved, size/XXL, release-note
