Repository tektoncd/cli, pull requests merged in 2023-08, with the labels that each got.

#2083 Add resolver support in tkn pr log commands
  pkg/cmd/pipelinerun/logs_test.go
  pkg/log/pipeline_reader.go
  test/e2e/pipelinerun/pipelinerun_test.go
  test/resources/pipelinerun-with-cluster-resolver.yaml
Labels: lgtm, approved, size/XL, release-note

#2102 Show error when there is an invalid filtered task
  pkg/log/pipeline_reader.go
Labels: size/XS, lgtm, approved, release-note

#2105 Support for Manifest annotations in `bundle push`
  docs/cmd/tkn_bundle_push.md
  docs/man/man1/tkn-bundle-push.1
  pkg/bundle/builder.go
  pkg/bundle/builder_test.go
  pkg/cmd/bundle/list_test.go
  pkg/cmd/bundle/push.go
  pkg/cmd/bundle/push_test.go
  pkg/params/mergeparams.go
  pkg/params/mergeparams_test.go
Labels: lgtm, approved, size/L, ok-to-test, release-note
