Repository tektoncd/cli, pull requests merged in 2023-05, with the labels that each got.

#2014 Remove flags from chains payload command as not used
  docs/cmd/tkn_chain_payload.md
  docs/man/man1/tkn-chain-payload.1
  pkg/cmd/chain/payload.go
Labels: lgtm, approved, size/S, release-note

#2006 Remove default value info for true flag in delete command
  docs/cmd/tkn_pipelinerun_delete.md
  docs/cmd/tkn_pipelinerun_list.md
  docs/cmd/tkn_taskrun_delete.md
  docs/cmd/tkn_taskrun_list.md
  docs/man/man1/tkn-pipelinerun-delete.1
  docs/man/man1/tkn-pipelinerun-list.1
  docs/man/man1/tkn-taskrun-delete.1
  docs/man/man1/tkn-taskrun-list.1
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/list.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/list.go
Labels: lgtm, approved, size/M, release-note

#2018 Upgrade golangci version to v1.52.2 and fix lint errors
  .golangci.yml
  Makefile
  cmd/docs/md_docs.go
  pkg/actions/get.go
  pkg/actions/list.go
  pkg/actions/patch.go
  pkg/cmd/clustertask/delete.go
  pkg/cmd/clustertriggerbinding/delete.go
  pkg/cmd/eventlistener/delete.go
  pkg/cmd/pipeline/delete.go
  pkg/cmd/pipeline/pipeline.go
  pkg/cmd/pipeline/sign.go
  pkg/cmd/pipeline/verify.go
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/task/delete.go
  pkg/cmd/task/sign.go
  pkg/cmd/task/task.go
  pkg/cmd/task/verify.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/triggerbinding/delete.go
  pkg/cmd/triggertemplate/delete.go
  pkg/deleter/deleter.go
  pkg/deleter/deleter_test.go
  pkg/formatted/completion.go
  pkg/test/dynamic/clientset/errorclient.go
  pkg/test/params.go
  pkg/trustedresources/verify.go
  pkg/version/version.go
  pkg/workspaces/workspaces.go
  test/builder/builder.go
  test/e2e/eventlistener/eventListener_test.go
  test/framework/helper.go
Labels: lgtm, approved, size/L, release-note

#2010 Fix tkn pr/tr delete command for keep flag
  pkg/cmd/pipelinerun/delete.go
  pkg/cmd/pipelinerun/delete_test.go
  pkg/cmd/taskrun/delete.go
  pkg/cmd/taskrun/delete_test.go
Labels: lgtm, approved, size/M, release-note

#2030 Bump tkn version in README to latest
  README.md
  choco/README.md
  choco/tektoncd-cli.nuspec
  choco/tools/chocolateyinstall.ps1
  releases.md
Labels: lgtm, approved, size/M, release-note-none

#2031 Use golang 1.19 in release pipeline
  tekton/release-pipeline.yml
Labels: size/XS, lgtm, approved, release-note-none

#2044 Bump golang to 1.19
  go.mod
Labels: size/XS, lgtm, approved, release-note

#2045 Bump chains to latest main
  go.mod
  go.sum
  vendor/github.com/go-openapi/spec/info.go
  vendor/github.com/go-openapi/spec/properties.go
  vendor/github.com/go-openapi/spec/responses.go
  vendor/github.com/go-playground/validator/v10/README.md
  vendor/github.com/go-playground/validator/v10/baked_in.go
  vendor/github.com/go-playground/validator/v10/country_codes.go
  vendor/github.com/go-playground/validator/v10/doc.go
  vendor/github.com/go-playground/validator/v10/struct_level.go
  vendor/github.com/go-playground/validator/v10/util.go
  vendor/github.com/go-playground/validator/v10/validator_instance.go
  vendor/github.com/google/trillian/client/admin.go
  vendor/github.com/google/trillian/client/backoff/backoff.go
  vendor/github.com/google/trillian/client/log_client.go
  vendor/github.com/google/trillian/client/log_verifier.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/keylib.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/model.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/slsa_provenance/v1/provenance.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/verifylib.go
  vendor/github.com/leodido/go-urn/makefile
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_latest.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/vnext.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/sigstore/rekor/pkg/pki/tuf/tuf.go
  vendor/github.com/sigstore/rekor/pkg/util/trillian_client.go
  vendor/github.com/tektoncd/chains/pkg/artifacts/signable.go
  vendor/github.com/tent/canonical-json-go/.travis.yml
  vendor/github.com/tent/canonical-json-go/LICENSE
  vendor/github.com/tent/canonical-json-go/encode.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/filtered/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/limitrange/limitrange.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/filtered/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/serviceaccount.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, release-note
