Repository tektoncd/cli, pull requests merged in 2024-11, with the labels that each got.

#2420 Set status to succeeded when the reason is Completed
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
Labels: lgtm, approved, size/S, release-note

#2427 refactor export function and add finalizers to be removed
  pkg/export/export.go
  pkg/export/export_test.go
Labels: lgtm, approved, size/L, release-note

#2429 Bump go to 1.22.8 and remove toolchain
  go.mod
Labels: size/XS, lgtm, approved, release-note

#2433 Use io.ReadFull to read the bundle content
  pkg/bundle/reader.go
Labels: kind/bug, size/XS, lgtm, approved, release-note

#2438 Do not print twice Cancelled when listing
  pkg/formatted/k8s.go
  pkg/formatted/k8s_test.go
Labels: lgtm, approved, size/S, release-note-action-required

#2440 Fix debbuild
  tekton/debbuild/control/control
Labels: size/XS, lgtm, approved, release-note
